### PR TITLE
Adding only boards with explicit access to default category

### LINKED ISSUE #4230: Bug: All synthetic-access boards end up displaying in sidebar
## Steps to reproduce the behavior

1. Create a channel and link multiple boards to it.
2. Signup as a new user and navigate to the channel in step 1.
3. Open any board from the boards RHS in channels.
4. Notice that all boards which were linked to the channel in step 1 end up being displayed in Boards LHS.

## Expected behavior

Only the board opened from channels RHS should show up in the Boards LHS.

## Edition and Platform

 - Edition: Mattermost Boards
 - Version: `main`

### PR DESCRIPTION
**Pull request by harshilsharma63**
Fixes #4230

The issue was, we were including all board memberships for the user - implicit and explicit. This caused all linked boards of all channels the user was part of when opening Boards for the first time. The fix is to include only boards with explicit memberships.

### CODE REVIEW

**Review by sbishel — APPROVED** [review]
I like the additional tests....

**Comment by harshilsharma63** [comment]
@ogi-m can you please test this out?

**Review by ogi-m — APPROVED** [review]
LGTM 👍🏻

**Pull request merged**
