### PR TITLE
Milotype translations

### PR DESCRIPTION
**Pull request by milotype**
#### Summary
Adding info about multilinguality in the ReadMe file as well as on the website.

### CODE REVIEW

**Comment by milotype** [comment]
@mattermod I'm not sure if I need to do anything. I am already on the list of [approved contributors](https://docs.google.com/spreadsheets/d/1NTCeG-iL_VS9bFqtmHSfwETo5f-8MQ7oMDE5IUYJi_Y/pubhtml?gid=0&single=true) as **milotype**

**Review by harshilsharma63 — DISMISSED** [review]

**Review by harshilsharma63 — APPROVED** [review]

**Comment by harshilsharma63** [comment]
@milotype can you resolve the merge conflitcs?

**Comment by harshilsharma63** [comment]
Looks fine to me but need your approval @chenilim @wuwinson

**Review by wuwinson — APPROVED** [review]
LGTM

**Comment by chenilim** [comment]
I apologize for the huge delay on this PR! The process should be that the core team reviewer merges the change after approving. I'll merge it now.

**Comment by milotype** [comment]
@chenilim Could you please check why the commit [Update hero.html](https://github.com/mattermost/focalboard/pull/1845/commits/eec16086c57398dabf2369c326ee2f1807786fa3) still doesn't sho on the website. Thank you.

**Pull request merged**
