### PR TITLE
update ubuntu to latest

### PR DESCRIPTION
**Pull request by sbishel**
#### Summary
Github deprecating ubuntu 18.04, use latest.

https://github.com/actions/runner-images/issues/6002
 > Workflows using the ubuntu-18.04 image label should be updated to ubuntu-latest, ubuntu-20.04, or ubuntu-22.04

### CODE REVIEW

**Comment by sbishel** [comment]
Not sure if should use latest or next available version to minimize potential issues. Tests run ok.

**Comment by wiggin77** [comment]
> Not sure if should use latest or next available version to minimize potential issues. Tests run ok.

I believe `lts` works here, which will bring down the latest LTS, which is what customers would be using versus the interim versions.

**Review by wiggin77 — APPROVED** [review]
LGTM :+1:

**Review by mgdelacroix — APPROVED** [review]
I'm happy using latest, LGTM! :+1:

**Pull request merged**
