### PR TITLE
Update CHANGELOG.md for v0.14 release

### PR DESCRIPTION
**Pull request by wuwinson**
#### Summary
v0.14 changes

### CODE REVIEW

**Comment by wiggin77** [comment]
@wuwinson it may be worth mentioning that the archive file format has changed and now supports images.

**Comment by wuwinson** [comment]
> 

Done! Thanks @wiggin77!

**Review by chenilim — APPROVED** [review]
Updated the casing for "Mac M1". Looks good!

**Review by sbishel — APPROVED** [review]

**Pull request merged**
