### PR TITLE
Update readme with accurate Linux standalone app build instructions

### PR DESCRIPTION
**Pull request by wiggin77**
#### Summary
This PR updates the readme to reflect changes to the standalone app build for Linux.  

#### Ticket Link
NONE

### CODE REVIEW

**Comment by chenilim** [comment]
cc @jespino. Shouldn't a developer be able to run the generated binary directly? Is the issue that certain pre-reqs are not in the same folder?

**Comment by wiggin77** [comment]
> cc @jespino. Shouldn't a developer be able to run the generated binary directly? Is the issue that certain pre-reqs are not in the same folder?

The only thing output to `dist` during a build is the gzipped file.  Some artefacts are put in `bin` but running from there just displays an empty window and no errors output.

**Comment by wuwinson** [comment]
Adding @chenilim as a reviewer instead. Updates to the readme look fine to me, but I'm not sure if anything should be added/changed. cc @wiggin77

**Review by chenilim — APPROVED** [review]
Thanks @wiggin77. This is a good change, because at least it gets the app working. Might just be a quick followup with @jespino if this is the expected workflow, and if something changed from the original.

**Pull request merged**
