### PR TITLE
Gh 2077 mac app update

### PR DESCRIPTION
**Pull request by chenilim**
#### Summary
This appears to be a timing issue in JS / React:
1. UseEffect in Boardpage.tsx subscribes and unsubscribes to workspace changes on the websocket (wsClient)
2. The cleanup routine returned from useEffect does the unsubscribe
3. With the Mac App (single-user), there's a pattern of useEffect, useEffect-cleanup, useEffect
4. However, in that last useEffect call, wsClient.state is 'init' (on [this line](https://github.com/mattermost/focalboard/blob/main/webapp/src/pages/boardPage.tsx#L206)), so subscribe isn't called
5. This is because wsClient is still somewhere in the [opening routine](https://github.com/mattermost/focalboard/blob/main/webapp/src/wsclient.ts#L259).

The fix is to update `wsClient.state` at the beginning of `ws.onopen`.

I've only observed this happening in the Mac App, and not in Safari against Personal Server. It's probably due to random differences in timing. There ultimately might be a more robust way to handle "re-entering" wsclient state changes, or change subscriptions.

#### Ticket Link
#2077

### CODE REVIEW

**Review by wiggin77 — APPROVED** [review]

**Comment by chenilim** [comment]
Thanks Doug. I propose cherry-picking this change for v0.12, as I think this is affecting customers (though I did not see any other reports in the feedback form or App Store).

The risk should be low, but what do you all think? cc @jespino, @sbishel, @ogi-m.

**Review by jespino — APPROVED** [review]
LGTM

**Comment by jespino** [comment]
Looks pretty low impact, so I'm ok merging it into 0.12. But here I prefer to get the @ogi-m opinion, If he doesn't feel comfortable with that, we can defer that until 0.13.

**Review by ogi-m — APPROVED** [review]
I can't say I'm too comfortable with this but given it's a one line change and if we think it's affecting customers, then let's cherry-pick it.

**Comment by chenilim** [comment]
Manually cherry-picked to release-0.12.

**Pull request merged**
