### PR TITLE
Update footer.html

### PR DESCRIPTION
**Pull request by varghesejose2020**
Update Year in  FocalBoard site Footer

### CODE REVIEW

**Review by wuwinson — APPROVED** [review]
Thanks @varghesejose2020! Looks good to me!

**Comment by varghesejose2020** [comment]
image
@wuwinson year in footer  not yet updated! `https://www.focalboard.com/`

**Comment by wuwinson** [comment]
Thanks @varghesejose2020. @asaadmahmood @sbishel This was merged to `main` a while back - do you know why it's not updated?

**Comment by asaadmahmood** [comment]
@wuwinson there are multiple steps that we need to take before the changes get deployed on focalboard.com.
See below:
https://docs.google.com/document/d/11uLGhYYNnsulL1oUAlfFyNcT3wgAiDJmCSvnNkuAbpA/edit#bookmark=id.4ll9apxeg6sr

**Comment by varghesejose2020** [comment]
Any updates?

**Comment by lindy65** [comment]
Hi @asaadmahmood - can you take a look at why this change is still not reflecting on the website please?  Thanks :)

**Pull request merged**
