### PR TITLE
Adding gif support for boards

### PR DESCRIPTION
**Pull request by asaadmahmood**
#### Summary
Adding gif support for boards

### CODE REVIEW

**Comment by chenilim** [comment]
@asaadmahmood, did you test an upload and display of a gif? Does that work?

There's code in [api.go here](https://github.com/mattermost/focalboard/blob/main/server/api/api.go#L1369) that sets the mime type based on the extension. I believe this needs to be extended for "image/gif" as well, for it to work correctly in all browsers.

**Comment by asaadmahmood** [comment]
@chenilim Yup, I uplodated a gif and it works. I can update it in that file as well.

**Review by wiggin77 — APPROVED** [review]
LGTM :+1:

**Review by chenilim — APPROVED** [review]

**Review by ogi-m — APPROVED** [review]
LGTM

**Pull request merged**
