### PR TITLE
Fixing style problems on hover editable board templates

### LINKED ISSUE #2216: Bug: New template selector > UI jitters when moving the mouse over custom templates
## Steps to reproduce the behavior

1. Create a few custom templates
2. Open the template selector
3. Move the cursor over the custom templates
4. Note that the UI jumps around as the width increases to accommodate the _edit_ and _delete_ butons

## Expected behavior

No jittering

## Screenshots

https://user-images.githubusercontent.com/15314183/152068499-ecf5228d-53df-40dd-bd36-273478b19f37.mp4

### LINKED ISSUE #2282: Bug: Personal Desktop > User can edit and delete default templates
## Steps to reproduce the behavior

1. Create a new Board template in Personal Desktop
2. Hover over the default templates
3. Delete and edit buttons appear on hover

## Expected behavior

Delete and edit buttons don't appear on hover

## Screenshots

Screenshot (168)

## Edition and Platform

 - Edition: Personal Desktop 
 - Version: v0.14
 - Browser and OS: Windows

### PR DESCRIPTION
**Pull request by jespino**
Fixes #2216
Fixes #2282

### CODE REVIEW

**Review by asaadmahmood — APPROVED** [review]

**Review by ogi-m — APPROVED** [review]
LGTM 👍🏻

**Comment by sbishel** [comment]
@jespino - There is a snapshot failing.

**Comment by jespino** [comment]
@ogi-m PTAL

**Comment by jespino** [comment]
@ogi-m nevermind, let me check something else before.

**Comment by jespino** [comment]
@ogi-m sorry, now should be working fine.

**Comment by jespino** [comment]
@ogi-m by the way, it also fixes the problem of showing the edit icon in the personal server app.

**Comment by ogi-m** [comment]
Thanks @jespino , verified this fixes https://github.com/mattermost/focalboard/issues/2282 as well

**Review by ogi-m — APPROVED** [review]

**Review by sbishel — APPROVED** [review]
LGTM

**Pull request merged**
