### PR TITLE
MM-40430 - Redirect user if already logged in

### PR DESCRIPTION
**Pull request by sbishel**
#### Summary
Updates Personal Server, so if a user is logged in, they are redirected when attempting to go to either
/login or  /register

Mattermost plugin already handles this correctly as `/boards/login` no longer exists.

#### Ticket Link

  Fixes https://mattermost.atlassian.net/browse/MM-40430

### CODE REVIEW

**Review by chenilim — APPROVED** [review]
LGTM!

**Review by harshilsharma63 — APPROVED** [review]

**Comment by sbishel** [comment]
@jesus Please review, regarding our discussion yesterday.

**Review by jespino — APPROVED** [review]
LGTM

**Comment by jespino** [comment]
@sbishel there are some conflicts, but it looks good to me.

**Pull request merged**
