### PR TITLE
Growth Spike - implement imports to help redirect

### PR DESCRIPTION
**Pull request by sbishel**
#### Summary
Add menu items for supported imports with link to help file. 

#### Ticket Link

https://community.mattermost.com/boards/workspace/qgsck6cts3fwpqwyjiupjm5cde/b4ctmm917q3rzdfi451qtuxjzcw/vpb5hydjzqtr7txbxeqpjxyfz4o/cackk6a45ptns8k8ojnqb1na6xc

### CODE REVIEW

**Comment by sbishel** [comment]
Ready to review, but do not merge until the links are live.

**Review by wiggin77 — APPROVED** [review]
LGTM 👍

**Review by harshilsharma63 — APPROVED** [review]
LGTM 👍

**Comment by harshilsharma63** [comment]
Changes look good but the docs link aren't working. Would they be available later?

**Review by justinegeffen — APPROVED** [review]

**Comment by justinegeffen** [comment]
@harshilsharma63, the docs aren't up yet and those are just placeholders for when they're published. :)

**Comment by harshilsharma63** [comment]
> @harshilsharma63, the docs aren't up yet and those are just placeholders for when they're published. :)

If they docs will be up when we release this in March, then it's fine.

**Comment by sbishel** [comment]
Now that v0.14 has been cut this can be merged.

**Pull request merged**
