### PR TITLE
Fixed bug of stale closure in markdown editor

### LINKED ISSUE #2036: Bug: Description updated by other sessions / users are overwritten on edit
## Steps to reproduce the behavior

1. Open a card
2. Set the description (e.g. "Desc 1")
2. Open the card in another tab
3. Edit the description in the first tab (e.g. "Desc 2"), second tab updates correctly
4. Now edit the description in the second tab
5. The editor shows "Desc 1"

## Expected behavior

The editor should show "Desc 2"

## Edition and Platform

 - Edition: Personal Desktop / Personal Server / Mattermost plugin
 - Version: v0.11 (Community server)
 - Browser and OS: Mac Chrome 96

### PR DESCRIPTION
**Pull request by harshilsharma63**
#### Summary
Fixes a bug with stale closure in markdown editor.

#### Ticket Link
Fixes #2036

### CODE REVIEW

**Review by sbishel — APPROVED** [review]
Tested and looks good.

**Comment by kamre** [comment]
@harshilsharma63 @sbishel after merging with `main` I was running Cypress tests and noticed this for comments:
image
Looks like this pull request has broken text editing in markdown editor component, i.e. cursor position is always reset to the beginning.

**Comment by sbishel** [comment]
I'll revert in a few minutes.

**Comment by sbishel** [comment]
Thanks for catching.. @kamre fix is here...
https://github.com/mattermost/focalboard/pull/2076/files

**Pull request merged**
