### PR TITLE
fix: fixes the dev setup dependencies issues when doing make linux-app

### PR DESCRIPTION
**Pull request by imasdekar**
#### Summary

- This PR adds a run for prebuild step that installs all the npm dependencies when doing make linux-app.

Signed-off by: imasdekar <imasdekar@disroot.org>

#### Ticket Link
Related Issue: #3221

### CODE REVIEW

**Review by Pinjasaur — COMMENTED** [review]
Hey @imasdekar, thanks for the PR!

I'm not familiar with using `--prefix` with `npm`. Do you have have any docs you could reference? I wasn't able to find much, it seems undocumented: https://github.com/npm/cli/issues/1368 I like that it cleans up the commands but would be concerned about making the commands themselves less clear.

And adding `prebuild` as a prereq to `linux-app` in the Makefile is a good addition. @chenilim do you know if it would be appropriate to add it as a prereq to for the Mac & Windows apps too?

**Comment by imasdekar** [comment]
@Pinjasaur the --prefix option is documented [here](https://docs.npmjs.com/cli/v7/using-npm/config#prefix)

Also, I fell that ideally the prebuild command should be added as a dependency to both windows and mac commands as well but I did not want to make a change which I was unable to test fully so I did not include it in my PR.

**Comment by wiggin77** [comment]
@imasdekar thanks for your PRs.  I suspect this PR stems from issues in our developer docs which we need to address.  I apologize for any frustration that caused.  Regarding this PR:

1. the `prebuild` step was intentionally kept separate to speed up the build, run, repeat cycle.  We do need to make it more clear in the docs.

2. The `--prefix` option for npm is undocumented for the use case here.  It is documented for `install` only.  I'm wary of relying on it versus sticking with something that works for all versions of npm past and future.

Let me know if you strongly disagree with any of the above.
Thanks.

**Comment by imasdekar** [comment]
@wiggin77 I do agree with both your points and we can close this MR.
We can update the docs with relevant info.
If no one is up for it at the moment then I can send an MR for the doc update.

**Comment by imasdekar** [comment]
@wiggin77 I have created an MR #3245 where I have updated the readme with the instructions for running the prebuild step.
I will shortly send the same update to the mattermost-developer-documentation as well.

**Pull request closed without merging**
