### PR TITLE
[GH-2147] URL property improvement

### LINKED ISSUE #2147: Feature Idea: URL property improvement
## Summary

Currently URL property is represented as an `input` element (sometimes readonly) and an additional `button` that appears on hover and allows to follow the link:

But how often do you need to _edit_ the link vs _follow_ the link? Probably following the link or even just copying the link are the actions that are used more often than editing.

Proposed changes:
* make the whole URL text as a clickable link via `a` element
* on hover show two buttons for editing and copying in the card dialog
* show only copy button for the cards on kanban/gallery/calendar views
* in the table cell two buttons take too much space so only show the button for editing

This is how URL property will look in the card dialog:

Also we can support markdown syntax for the links so that displayed text can be entered by the user:

## How important this is to me and why

Importance: Medium, nice to have feature

## Additional context/similar features

Notion URL property works like this and it is rather convenient.

@chenilim @wuwinson @asaadmahmood what do you think about such improvement for URL property?

### PR DESCRIPTION
**Pull request by kamre**
#### Summary

URL property was changed according to the requirements in #2147:
- rendered as a link with buttons for editing and copying that are visible on hover
- compass icon is used for `EditIcon`
- labels for view menu and view header menu fixed
- unit tests for new URL property behaviour added
- cypress test for URL property added
- minor fixes for card in the calendar view

Here is how it looks in the card dialog:

Here is how it looks for kanban card:

#### Ticket Link

Fixes #2147 

@saturninoabril please review the cypress test, I had to use [cypress-real-events](https://github.com/dmtrKovalenko/cypress-real-events) library for proper hover events

### CODE REVIEW

**Comment by chenilim** [comment]
Thanks for submitting this @kamre! Also looping in @harshilsharma63 (webapp code) and @asaadmahmood (please review the icon changes in particular).

**Comment by harshilsharma63** [comment]
Awesome feature @kamre ! Changes look great! One change request though. @asaadmahmood can comment on UI/UX part.

**Review by harshilsharma63 — CHANGES_REQUESTED** [review]
Awesome work 🎉 One change needed though: when in edit mode, can we have the mouse pointer as a cursor?

**Review by harshilsharma63 — APPROVED** [review]

**Comment by harshilsharma63** [comment]
> @harshilsharma63 it seems that we have _mouse cursor_ as `pointer` for _all text properties_ currently, for example `Text`, `Email` have this cursor. Should this also be changed?

Hmm, I didn't notice that. If that's the case, we should update that in a separate ticket. Approved this now.

**Comment by kamre** [comment]
@harshilsharma63 the change for all text properties can look like this:
```diff
Index: webapp/src/components/cardDetail/cardDetail.scss
===================================================================
diff --git a/webapp/src/components/cardDetail/cardDetail.scss b/webapp/src/components/cardDetail/cardDetail.scss
--- a/webapp/src/components/cardDetail/cardDetail.scss	(revision f4bf7db996ce2df3602778bd1a6a116cfc7f5990)
+++ b/webapp/src/components/cardDetail/cardDetail.scss	(revision c368423a71cb3792de45abac210525e7f3950058)
@@ -67,9 +67,12 @@
             &:not(.readonly) {
                 min-width: 180px;
                 transition: background 100ms ease-out 0s;
-                cursor: pointer;
                 border-radius: 4px;
 
+                &:not(.Editable) {
+                    cursor: pointer;
+                }
+
                 &:hover {
                     background-color: rgba(var(--center-channel-color-rgb), 0.08);
                 }
```
Should I apply it in this pull request?

**Review by asaadmahmood — APPROVED** [review]
LGTM!

**Review by ogi-m — APPROVED** [review]
LGTM, thanks @kamre !

**Pull request merged**
