### PR TITLE
Added a Dialog notification after clicking on the Cards hidden button

### PR DESCRIPTION
**Pull request by Rajat-Dabade**
#### Summary
This PR adds the feature to notify users using the Dialog box about the hidden card count when clicking on Cards hidden button.

#### Ticket Link

Fixes https://github.com/mattermost/focalboard/issues/3178

### CODE REVIEW

**Comment by Rajat-Dabade** [comment]
@sbishel, I have already used the template which is implemented by @jespino i.e. [notification-box.tsx](https://github.com/mattermost/focalboard/blob/release-7.0/webapp/src/widgets/notification-box.tsx).  I guess [cardLimitNotification.tsx](https://github.com/mattermost/focalboard/blob/release-7.0/webapp/src/components/cardLimitNotification.tsx) is specifically for Card Limit Notification. I have also cleared the snoozing part and it is working as expected.

**Review by harshilsharma63 — APPROVED** [review]
LGTM 👍

**Review by sbishel — APPROVED** [review]

**Comment by sbishel** [comment]
Looks good. Don't forget you will need port this to `main` as well.

**Comment by Rajat-Dabade** [comment]
Sure, will merge it to main

**Pull request merged**
