### PR TITLE
[GH-1539] Implement searching for the individual words in workspaces

### PR DESCRIPTION
**Pull request by De1ain**
Implement searching for the individual words in workspaces

Old behavior:
Simply checking if a search query is a substing of any workspace name, by using `includes` function
New behavior: 
Search now looks for any word (or part of it) from the search query in the names of all workspaces.

Examples: 
Have workspaces:  'Workspace 1', 'Workspace 2', and 'Workspace 3'.
Searching for 'Workspace 1' will find all 3 workspaces, because each one contains the word 'workspace'.

Have workspaces: 'Foo Bar Baz'
Seaching for 'foo baz' will find 'Foo Bar Baz'

Update:
Updated first search test name with some description. Updated it's snapshot, according to the new search algorithm changes.
Updated the search filter of the second search test to not include the work workspace, since it will find all 3 workspaces that contain this word.
Add 2 new sample workspace with unique names.
Add 2 new tests.

Fixes https://github.com/mattermost/focalboard/issues/1539

### CODE REVIEW

**Comment by harshilsharma63** [comment]
@ogi-m bump :)

**Review by ogi-m — COMMENTED** [review]
Thanks @De1ain. One issue I'm seeing is this:

1. Set up 5 workspaces:
- Workspace
- Workspace 1
- Workspace 11
- Workspace 2
- Workspace 3
2. Search on the dashboard, by typing in "workspace"

**Observed**: Workspace, Workspace 2, Workspace 3 are returned but Workspace 1 and Workspace 11 are not
**Expected**: All 5 workspaces are returned

**Comment by De1ain** [comment]
@ogi-m Thanks for testing
It seems like this change ed0a339dfdeb2d8621f17821e3d3105e44b5b3f7 introduced this bug.
Investigating...

**Comment by emilyacook** [comment]
Thanks for participating in Hacktoberfest! You can claim your sticker set here: https://get.printfection.com/hacktober21/4144583267 @De1ain

**Comment by De1ain** [comment]
Fixed in d13d640.

Changed the title search pattern.
Added new test cases and dummy workspaces.

**Comment by ogi-m** [comment]
Thanks @De1ain , LGTM 👍🏻

**Review by ogi-m — APPROVED** [review]

**Review by hahmadia — APPROVED** [review]

**Pull request merged**
