### PR TITLE
Feature/adjust board component scroll

### PR DESCRIPTION
**Pull request by signalwerk**
This PR intends to enhance the scroll experience for the board component. Right now the Header scrolls away and the info is not accessible anymore.

## Current
Screenshot 2021-04-24 at 04 07 38

## New
Screenshot 2021-04-24 at 04 08 18

## Other
For the future it would be good to also have the following features

* Collapse the header to save space
* Have the header of the columns  of Kanban-View and Table-View also sticky

### CODE REVIEW

**Review by jespino — APPROVED** [review]
I like this, and I think is a step forward in the right direction, I think we need to think more about it. I think is fine to merge it, and continue from there.

**Comment by jespino** [comment]
Cypress tests are failing, but I guess I can figure out why for you.

**Review by hahmadia — APPROVED** [review]
Nice! I like this change a lot and also feel it's a big improvement from what is currently there. Thank you 🙏

**Comment by harshilsharma63** [comment]
I'm trying to get this to work.

**Comment by harshilsharma63** [comment]
I'm closing this PR in favour of https://github.com/mattermost/focalboard/pull/447 . That other PR contains the fixes for Cypres tests and a few more improvements over the already awesome work done here 🤘

**Comment by signalwerk** [comment]
@harshilsharma63 tanks a lot!

**Comment by hanzei** [comment]
@harshilsharma63 Should this be closed?

**Comment by harshilsharma63** [comment]
@hanzei yes, this should be closed.

**Pull request closed without merging**
