### PR TITLE
Fixing jest tests

### PR DESCRIPTION
**Pull request by jespino**

### CODE REVIEW

**Comment by kamre** [comment]
Hi @jespino, here is a possible fix for Cypress tests:
```diff
Index: webapp/cypress/support/api_commands.ts
===================================================================
diff --git a/webapp/cypress/support/api_commands.ts b/webapp/cypress/support/api_commands.ts
--- a/webapp/cypress/support/api_commands.ts	(revision aa9ebc237fc162c1c98a9ff02cff4389bc539c83)
+++ b/webapp/cypress/support/api_commands.ts	(date 1648577742601)
@@ -52,32 +52,32 @@
     return cy.apiRegisterUser(data, '', false).apiLoginUser(data)
 })
 
-Cypress.Commands.add('apiDeleteBlock', (id: string) => {
+Cypress.Commands.add('apiDeleteBoard', (id: string) => {
     return cy.request({
         method: 'DELETE',
-        url: `/api/v1/workspaces/0/blocks/${encodeURIComponent(id)}`,
+        url: `/api/v1/boards/${encodeURIComponent(id)}`,
         ...headers(),
     })
 })
 
-const deleteBlocks = (ids: string[]) => {
+const deleteBoards = (ids: string[]) => {
     if (ids.length === 0) {
         return
     }
     const [id, ...other] = ids
-    cy.apiDeleteBlock(id).then(() => deleteBlocks(other))
+    cy.apiDeleteBoard(id).then(() => deleteBoards(other))
 }
 
 Cypress.Commands.add('apiResetBoards', () => {
     return cy.request({
         method: 'GET',
-        url: '/api/v1/workspaces/0/blocks?type=board',
+        url: '/api/v1/teams/0/boards',
         ...headers(),
     }).then((response) => {
         if (Array.isArray(response.body)) {
             const boards = response.body as Board[]
             const toDelete = boards.filter((b) => !b.isTemplate).map((b) => b.id)
-            deleteBlocks(toDelete)
+            deleteBoards(toDelete)
         }
     })
 })
Index: webapp/cypress/global.d.ts
===================================================================
diff --git a/webapp/cypress/global.d.ts b/webapp/cypress/global.d.ts
--- a/webapp/cypress/global.d.ts	(revision aa9ebc237fc162c1c98a9ff02cff4389bc539c83)
+++ b/webapp/cypress/global.d.ts	(date 1648577742596)
@@ -15,7 +15,7 @@
         apiGetMe: () => Chainable<string>
         apiChangePassword: (userId: string, oldPassword: string, newPassword: string) => Chainable
         apiInitServer: () => Chainable
-        apiDeleteBlock: (id: string) => Chainable
+        apiDeleteBoard: (id: string) => Chainable
         apiResetBoards: () => Chainable
         apiSkipTour: (userID: string) => Chainable
 
Index: webapp/cypress/integration/cardURLProperty.ts
===================================================================
diff --git a/webapp/cypress/integration/cardURLProperty.ts b/webapp/cypress/integration/cardURLProperty.ts
--- a/webapp/cypress/integration/cardURLProperty.ts	(revision aa9ebc237fc162c1c98a9ff02cff4389bc539c83)
+++ b/webapp/cypress/integration/cardURLProperty.ts	(date 1648576013522)
@@ -97,7 +97,7 @@
     const addView = (type: ViewType) => {
         cy.log(`**Add ${type} view**`)
         cy.findByRole('button', {name: 'View menu'}).click()
-        cy.findByText('Add view').click()
+        cy.findByText('Add view').realHover()
         cy.findByRole('button', {name: type}).click()
         cy.findByRole('textbox', {name: `${type} view`}).should('exist')
     }
Index: webapp/cypress/integration/loginActions.ts
===================================================================
diff --git a/webapp/cypress/integration/loginActions.ts b/webapp/cypress/integration/loginActions.ts
--- a/webapp/cypress/integration/loginActions.ts	(revision aa9ebc237fc162c1c98a9ff02cff4389bc539c83)
+++ b/webapp/cypress/integration/loginActions.ts	(date 1648575844735)
@@ -11,7 +11,7 @@
         cy.log('**Redirects to error then login page**')
         cy.visit('/')
         cy.location('pathname').should('eq', '/error')
-        cy.get('button').contains('Login').click()
+        cy.get('button').contains('Log in').click()
         cy.location('pathname').should('eq', '/login')
         cy.get('.LoginPage').contains('Log in')
         cy.get('#login-username').should('exist')
Index: webapp/cypress/integration/createBoard.ts
===================================================================
diff --git a/webapp/cypress/integration/createBoard.ts b/webapp/cypress/integration/createBoard.ts
--- a/webapp/cypress/integration/createBoard.ts	(revision aa9ebc237fc162c1c98a9ff02cff4389bc539c83)
+++ b/webapp/cypress/integration/createBoard.ts	(date 1648576099048)
@@ -98,7 +98,7 @@
         // Create table view
         cy.log('**Create table view**')
         cy.get('.ViewHeader').get('.DropdownIcon').first().parent().click()
-        cy.get('.ViewHeader').contains('Add view').click()
+        cy.get('.ViewHeader').contains('Add view').realHover()
         cy.get('.ViewHeader').
             contains('Add view').
             parent().
```

**Review by chenilim — APPROVED** [review]
LGTM

**Review by sbishel — APPROVED** [review]

**Comment by sbishel** [comment]
Merging as this fixes and passes jest tests. Need this merged to ensure cypress tests pass in other PR.

**Comment by chenilim** [comment]
WOOHOO! CI is passing again on main! Thank you everyone for getting this to green. Special thanks to you @kamre! Really appreciate it!

**Pull request merged**
