### PR TITLE
Additional new standard board templates

### PR DESCRIPTION
**Pull request by wuwinson**
#### Summary
Added 6 additional standard board templates for:
1. Company Goals & OKRs
2. Competitive Analysis
3. Sales Pipeline CRM
4. Sprint Planner
5. Team Retrospective
6. User Research Sessions

#### Ticket Link
https://community.mattermost.com/boards/team/qghzt68dq7bopgqamcnziq69ao/b4ctmm917q3rzdfi451qtuxjzcw/vuswsftt1rb873datosmmbtwkpa/cj468c1cq73d43mktuhzc8x84ua

### CODE REVIEW

**Comment by wuwinson** [comment]
@wiggin77 @sbishel Not sure what I did wrong, but my PR didn't seem to work. Just uploaded the plugin file from this PR to my test server and still don't see the new templates.

**Comment by sbishel** [comment]
I think you also need to update - https://github.com/mattermost/focalboard/blob/main/server/assets/templates-boardarchive/version.json

**Comment by wuwinson** [comment]
Can I just change the version to `3`? Is there something specific I need for the date portion?

Screen Shot 2022-11-04 at 10 30 06 AM

**Comment by wuwinson** [comment]
Success! Thanks for your help guys! Can we get this reviewed and merged in?

Screen Shot 2022-11-04 at 3 52 51 PM

**Review by wiggin77 — APPROVED** [review]
LGTM :+1:

**Review by sbishel — APPROVED** [review]

**Pull request merged**
