### PR TITLE
Cherry pick PR 3552

### PR DESCRIPTION
**Pull request by wiggin77**
#### Summary
Manual cherry-pick of https://github.com/mattermost/focalboard/pull/3552 and fix merge conflict.

#### Ticket Link
NONE

### CODE REVIEW

**Review by jespino — APPROVED** [review]
LGTM

**Review by sbishel — APPROVED** [review]
You will get an error in tests, I have a pr to fix.
https://github.com/mattermost/focalboard/pull/3562

Closing...
https://github.com/mattermost/focalboard/pull/3560

**Comment by wiggin77** [comment]
> You will get an error in tests, I have a pr to fix.

Ok, I'll update-branch when that gets merged.

**Comment by jespino** [comment]
I fixed it as part of my previous cherry-pick so... it should be fixed now.

**Pull request merged**
