### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by hastadhana**
Fix "already" word.

### CODE REVIEW

**Review by jespino — APPROVED** [review]
Looks good to me. Thanks @hastadhana! :tada:

**Comment by jespino** [comment]
@hastadhana we need you to sign the CLA to merge you PR. Let me know when is signed and I'll merge the PR.

**Comment by hastadhana** [comment]
I have signed the CLA. Thanks @jespino! 😃

**Review by jespino — APPROVED** [review]
Thanks! :tada:

**Pull request merged**
