### PR TITLE
fix string vs string[] in hiding rows

### LINKED ISSUE #4479: Bug: Group by Person, collapsed still shows item.
## Steps to reproduce the behavior

1. Go to board, add person property, set cards 
2. Select  Group By...Person property (table view)
3. Collapse one of the person categories.
4. See one card (line) is still visible

## Expected behavior

All cards for that category (person) should be hidden.

## Screenshots (optional)
Screen Shot 2023-01-17 at 11 41 45 AM

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: [Person-filter PR]
 - Browser and OS: 
Chrome on Mac

## Additional context (optional)

Add any other context about the problem here, and any notes about the severity:
* Sev 1: Affects critical functionality without a workaround
* Sev 2: Affects major functionality with a difficult or non-obvious workaround
* Sev 3: Affects minor, non-critical functionality

### PR DESCRIPTION
**Pull request by sbishel**
#### Summary
Fixes a couple different issues related to the original issue - 
 - In the confirmPerson, adding a user always added as an array. Update to check for `multiperson` type to save as array. However, there may be Person properties already stored as an array, so check for array and use first element if it is an array. 

When testing I converted the property types and also noticed issues with property type conversions. 
This PR also updates conversion to/from Person properties using the following rules.
 - Person -> MultiPerson - just store string as array.
 - MultiPerson -> Person - store multiPerson.value[0]
 - Either -> another property - clear property (Empty)
 - another property -> either - clear property (Empty)

#### Ticket Link

  Fixes #4479

### CODE REVIEW

**Comment by sbishel** [comment]
@wuwinson - Please review the rules I used for migrating to/from person and multi-person properties and let me know if you want any handled differently.

**Comment by wuwinson** [comment]
> @wuwinson - Please review the rules I used for migrating to/from person and multi-person properties and let me know if you want any handled differently.

What you have there looks good to me!

**Review by harshilsharma63 — APPROVED** [review]
LGTM 👍

**Comment by sbishel** [comment]
@ogi-m - ping on this, I would like to test before merging.

**Review by ogi-m — APPROVED** [review]
Tested and passed
- issue with collapsing person categories is fixed
- converting person property to multiperson working as expected
- converting person multiperson to person retains the first selected user
- converting from other properties to person or multiperson or vice versa clears the property

**Comment by sbishel** [comment]
Thanks @ogi-m!

**Pull request merged**
