### PR TITLE
Upgrade Scorecards action version

### PR DESCRIPTION
**Pull request by mgdelacroix**
#### Summary
Updates scorecard action version to fix CI in `main`

### CODE REVIEW

**Comment by mgdelacroix** [comment]
Tested in [this CI run](https://github.com/mattermost/focalboard/actions/runs/5154417347/jobs/9282855410?pr=4760)

**Review by sbishel — APPROVED** [review]
@mgdelacroix - Will this need cp'ed to release-7.11?

**Comment by mgdelacroix** [comment]
@sbishel I'd do it just to get the CI green, it really only affects the scorecard action which is purely informative, it has no other implications

**Pull request merged**
