### PR TITLE
[GH-2442] Improve performance for table column resize

### LINKED ISSUE #2442: Bug: Resizing a table column is unusably slow
## Steps to reproduce the behavior

1. Open a table view
2. Drag to resize the first column (or any column)
3. The live resizing lags and is pretty much unusable

## Expected behavior

Resizing should be fast and easy

## Screenshots

https://user-images.githubusercontent.com/46905241/156465311-83bddc5d-cdb1-4e37-82ba-09740c7a4e7f.mov

## Edition and Platform

 - Edition: Mattermost plugin
 - Version: v0.14.0
 - Browser and OS: Chrome on Mac

## Additional context

This may be caused by the live-resizing. Recommend either improving the live-resizing, or replacing it with resize-on-mouse-up.

### PR DESCRIPTION
**Pull request by kamre**
#### Summary
Resizing of table column was reimplemented:
- don't use react props for column widths to avoid extremely slow react rerendering
- don't use `react-dnd` for `HorizontalGrip` because it has significant overhead
- maintain references to table cell elements in new react context `ColumnResizeContext`
- modify inline width style for table cell directly while resizing the column
- use mouse events for `HorizontalGrip`

Resizing works with acceptable performance even on large tables like this one:

https://user-images.githubusercontent.com/5587620/167008151-3795c59b-4eb5-42db-9d74-8bac77c7e59e.mov

#### Ticket Link
Fixes #2442

### CODE REVIEW

**Comment by LimitlessDonald** [comment]
Hello @kamre thanks for your work. Do you think your changes would fix this issue here : https://github.com/mattermost/focalboard/issues/2907 ?

KIndly check thanks .

**Comment by kamre** [comment]
Hello @LimitlessDonald, this pull request _only fixes the column resizing performance_ and not "create a new task in table view".

**Comment by LimitlessDonald** [comment]
OK thanks. Part of the issue I reported actually includes the column having
issues with resizing if there are many tasks. So I taught all the issues
are related and your fix probably solved them all .

**Review by wiggin77 — APPROVED** [review]
LGTM :+1:   Great work @kamre!

**Review by harshilsharma63 — APPROVED** [review]
Awsome! LGTM 👍

**Review by asaadmahmood — APPROVED** [review]
LGTM

**Review by Pinjasaur — APPROVED** [review]
LGTM, nice work @kamre! 🎉

**Pull request merged**
