### PR TITLE
Fixed a bug preventing new template being created from a card

### LINKED ISSUE #1888: Bug: Unable to create new card from a template
## Steps to reproduce the behavior

1. Try to create a new card from a template
2. See error

## Screenshots

I get this card when I try to create a new card from a pre-existing template.

Screenshot 2021-11-29 at 11 34 47 PM

## Edition and Platform

 - Edition: Personal Server
 - Version: v0.11.0
 - Browser and OS: Safari & MacOS

### PR DESCRIPTION
**Pull request by harshilsharma63**
#### Summary
Fixed a bug preventing new template being created from a card

#### Ticket Link
Fixes #1888

### CODE REVIEW

**Comment by harshilsharma63** [comment]
@ogi-m  I've fixed the part where creating a template from a card shows the error but have left the part where an error message is displayed for a split second when creating a new card from a template. This is done in the interest of time as it doesn't affect anything in Boards.

**Review by mgdelacroix — APPROVED** [review]
LGTM! :+1:

**Comment by harshilsharma63** [comment]
@ogi-m can you please test this before I merge and cherrypick this?

**Review by ogi-m — APPROVED** [review]
Thanks @harshilsharma63, LGTM. I'll file a separate ticket for the brief error.

**Pull request merged**
