### PR TITLE
Added overflow wrap to boardCard

### PR DESCRIPTION
**Pull request by BharatKalluri**
#### Summary
A very small change to add wrap to boardCard

#### Ticket Link
Fixes https://github.com/mattermost/focalboard/issues/184

### CODE REVIEW

**Comment by asaadmahmood** [comment]
@BharatKalluri Does it work fine for you? `anywhere` has less browser support, so wondering if that's going to cause an issue.

**Comment by jespino** [comment]
@asaadmahmood I think it is safe to merge this, in the worst case scenario, is going to be reported again in an specific environment. It works for me in firefox.

**Review by jespino — APPROVED** [review]
Looks good to me. Thanks @BharatKalluri! :confetti_ball:

**Comment by BharatKalluri** [comment]
Hi @asaadmahmood , I've tested this in firefox, chrome and brave in mac. I'll go home and give it a test in Linux. It worked for me in mac in all the browsers I've tested. If I find it to be a problem anywhere, I'll make a follow up PR 😄 

Thanks @jespino !

**Pull request merged**
