### PR TITLE
[GH-40] Add property type email

### PR DESCRIPTION
**Pull request by renjithgr**
#### Summary

This PR adds the option to choose email as a field type.

image

#### Ticket Link
#40 

Most of the components are not covered by unit tests, including the ones I changed. So I was not sure what strategy the creators have in mind for unit testing components. Please advise. I would be happy to add unit tests.

Thank you!

### CODE REVIEW

**Comment by jespino** [comment]
@renjithgr unit tests are really welcome, we want to have a good test coverage, we have implemented this without unit testing to move fast in this stage of the process, but we will add them for sure sooner than later.

**Comment by renjithgr** [comment]
Thanks for your feedback, @jespino. Let me know if you want me to add unit tests in this PR or you want to go ahead without unit tests for now. I would be happy to raise another PR to add unit tests.

**Comment by jespino** [comment]
@renjithgr Lets merge this in, and add the unit tests in another PR. :)

**Review by jespino — APPROVED** [review]
Looks good to me. Thanks @renjithgr! :tada:

**Pull request merged**
