### PR TITLE
Update ubuntu.md

### PR DESCRIPTION
**Pull request by NvL-WEAP**
#### Summary

Correction in postgres connection string example.

### CODE REVIEW

**Review by jespino — APPROVED** [review]
Thanks @NvL-WEAP! :confetti_ball:

**Comment by jespino** [comment]
@NvL-WEAP to merge this in I need you to sign the CLA. It is ok if you don't want to sign it, but then I can't merge the PR.

**Comment by harshilsharma63** [comment]
@NvL-WEAP in Postgres `postgres://` and "postgresql://` are interchangeable, as also mentioned in the official docs - https://www.postgresql.org/docs/10/libpq-connect.html .

Are you facing any issue running Focalboard with `postgres://` instead of `postgresql://`?

**Comment by harshilsharma63** [comment]
Closing as not needed.

@NvL-WEAP feel free to reopen if needed.

**Pull request closed without merging**
