### PR TITLE
Improvements for multi-select property

### PR DESCRIPTION
**Pull request by kamre**
#### Summary
Minor fixes for multi-select property:
- width of delete icon is set to 16px so that value text is not truncated
- don't close menu for multi-select when value is selected or unselected
- support `Escape` and `Backspace` keys while editing
- unit tests updated and two more added

Here is how it looks:
| Before | After |
|---|---|
|| |

### CODE REVIEW

**Comment by kamre** [comment]
@asaadmahmood @wuwinson can you please also review from the UX side?

**Comment by asaadmahmood** [comment]
Looks good @kamre

**Comment by wuwinson** [comment]
Very nice! Thanks @kamre!

**Comment by kamre** [comment]
Hi @jespino, I have rebased the branch on `main`, please review.

**Review by jespino — APPROVED** [review]
Sorry for the late review, Looks good to me. Thanks @kamre, as always, really valuable contribution. :heart:

**Review by harshilsharma63 — APPROVED** [review]

**Comment by harshilsharma63** [comment]
@kamre awesome work as usual! Can you look at the webapp build failure that's occurring after syncing with `main`?

**Comment by kamre** [comment]
Hi @harshilsharma63, fixed `ValueSelector`, jest tests are passing for me locally.

But I am not able to build the server now with the following error:
```
 focalboard git:(multi-select-fix) make server
go run ./build/gowork/main.go
go.work already exists and -f (force) not specified; nothing to do.
cd server; go build -ldflags '-X "github.com/mattermost/focalboard/server/model.BuildNumber=dev" -X "github.com/mattermost/focalboard/server/model.BuildDate=n/a" -X "github.com/mattermost/focalboard/server/model.BuildHash=ee9ce5b5b0f1c43935723fe12d990425bcdf2cdb" -X "github.com/mattermost/focalboard/server/model.Edition=dev"' -tags 'json1 sqlite3' -o ../bin/focalboard-server ./main
# github.com/mattermost/focalboard/server/api
api/insights.go:116:31: undefined: model.GetStartOfDayForTimeRange
api/insights.go:234:31: undefined: model.GetStartOfDayForTimeRange
# github.com/mattermost/mattermost-server/v6/store/sqlstore
../../../go/pkg/mod/github.com/mattermost/mattermost-server/v6@v6.0.0-20220802151854-f07c31c5d933/store/sqlstore/store.go:1022:41: undefined: mysql.Config
../../../go/pkg/mod/github.com/mattermost/mattermost-server/v6@v6.0.0-20220802151854-f07c31c5d933/store/sqlstore/store.go:1029:60: undefined: postgres.Config
make: *** [server] Error 2
```

**Comment by kamre** [comment]
@harshilsharma63 thanks, updating to the latest mattermost server and webapp fixed building the server.

**Review by ogi-m — APPROVED** [review]
Works great 🎉

**Pull request merged**
