### PR TITLE
check createdBy instead of team id to determine global templates

### PR DESCRIPTION
**Pull request by sbishel**
#### Summary
Personal desktop/server does not support teams. Therefore the only teamId in these products is "GlobalTeamID" = 0. When we determine if a template can be edited, we check the teamId field which is fine for plugin because only the global templates will use GlobalTeamID. However, because the only team on Personal Desktop/Server is 0. We need another way to check for GlobalTemplates, moved to using the `CreatedBy` field and added a constant for 'system' which is listed as the creator of global templates.

#### Ticket Link
  Fixes https://github.com/mattermost/focalboard/issues/3695

### CODE REVIEW

**Review by Pinjasaur — APPROVED** [review]
LGTM, didn't realize we didn't have that constant used on the frontend 'til this point 👍🏻 

I'm going to defer merging immediately because I'm not able to personally confirm functionality locally as I'm getting migration errors. Potentially related to #3774 cc @harshilsharma63 I'll post my logs in that issue

**Comment by Pinjasaur** [comment]
still broken for me locally after #3774 merge https://community.mattermost.com/boards/team/qghzt68dq7bopgqamcnziq69ao/2b3ba61b-2434-4892-8fe0-f22fe5af5e68/a43d6c7d-bf99-4ee2-8697-32071ab11207/csxa4s4yjmbdwpecbyj4omp4hgr

**Comment by sbishel** [comment]
That issue appears unrelated to this PR

**Pull request merged**
