### PR TITLE
Fixed menu label hover

### LINKED ISSUE #1469: Bug: "Select a template" (on add Board list) looks like a button but it is not
## Steps to reproduce the behavior

1. Go to Focalboard
2. Click on "Add Board"
3. Mouse hover the label "Select a template"
The mouse pointer and the background color of the field are like it is a button but clicking is not doing something.

## Expected behavior

The mouse pointer and the background color are not like it is a button.

## Screenshots

Select a template

## Edition and Platform

 - Edition: Personal Desktop
 - Version: v0.8.0
 - Browser and OS: Windows app, Windows

## Additional context

N/A

### PR DESCRIPTION
**Pull request by JenyaFTW**
#### Summary
Disabled menu label hover. Just removing hover alone didn't help so needed to add `pointer-events: none`

#### Ticket Link
Fixes #1469

### CODE REVIEW

**Comment by hahmadia** [comment]
Hi @JenyaFTW ,

Sorry for the delay. You had not re-requested a review so the PR had not come up in our list of PR's to review for myself and my colleague Harshil.

Could you please fix the broken tests and get the CI build to pass before we do another round of review. Thank you

**Review by hahmadia — APPROVED** [review]
LGTM. It worked.

@harshilsharma63 feel free to merge if also working for you.

**Review by harshilsharma63 — APPROVED** [review]

**Comment by emilyacook** [comment]
Thanks for participating in Hacktoberfest! You can claim your sticker set here: https://get.printfection.com/hacktober21/4144583267 @JenyaFTW

**Pull request merged**
