### PR TITLE
Updating board template picker ui

### PR DESCRIPTION
**Pull request by asaadmahmood**
#### Summary
Updating board template picker ui to include the use template button in the header, and empty board button in the sidebar, so the buttons do not overlap the content.

Additionally, made the UI scalable on larger screen sizes so scroll on the sidebar can be avoided.

#### Screenshot
Screenshot 2022-11-16 at 12 17 28 AM
Screenshot 2022-11-16 at 12 17 44 AM

### CODE REVIEW

**Comment by wuwinson** [comment]
@asaadmahmood Tested it out the PR, and I'm seeing this:
Screen Shot 2022-11-15 at 10 43 00 AM

Also concerned that the new button location blends in too much with the template, so it's not obvious that it's clickable. What if we tried shifting the buttons down instead, so it's outside of the preview box?

Screen Shot 2022-11-15 at 10 45 27 AM

**Comment by Pinjasaur** [comment]
@ogi-m could you give this a once-over on linux or windows? mostly interested in vetting it on a different OS that doesn't "swallow" scrollbars

**Review by Pinjasaur — APPROVED** [review]
overall LGTM, nice work @asaadmahmood! 🎉 

2 nits:

1. I wish the `Use this template` button wasn't so far from the list of templates
2. when testing it locally on I found the template preview to be a bit short i.e. I was _wanting_ to see more of the preview (see screenshot). maybe it could be taller, could have a scrollbar, or it doesn't matter 🤷🏻 

image

**Comment by asaadmahmood** [comment]
@Pinjasaur Added the scrollbar, and reduced the padding on the edges of the modal, making the modal taller on smaller sizes.

**Review by ogi-m — APPROVED** [review]
I don't have a Windows machine up and running yet, so I don't want to block the PR for today's cloud cut off

**Pull request merged**
