### PR TITLE
remove BoardsUnfurl feature flag

### PR DESCRIPTION
**Pull request by sbishel**
#### Summary
Removes the BoardsUnfurl feature flag

#### Ticket Link
Fixes https://github.com/mattermost/focalboard/issues/1973

### CODE REVIEW

**Review by wiggin77 — APPROVED** [review]
LGTM 👍

**Review by jespino — APPROVED** [review]
LGTM

**Review by harshilsharma63 — APPROVED** [review]
LGTM 👍

**Pull request merged**
