### PR TITLE
Issue 678 - Updating default dark theme label

### PR DESCRIPTION
**Pull request by asaadmahmood**
#### Summary
Issue 678 - Updating default dark theme label

#### Ticket Link
https://github.com/mattermost/focalboard/issues/678

#### Screenshot
Screenshot 2021-07-14 at 8 30 18 PM

### CODE REVIEW

**Review by wiggin77 — COMMENTED** [review]
The new text color has a yellow tint.  Is that intended?

**Review by wiggin77 — APPROVED** [review]

**Comment by asaadmahmood** [comment]
@wiggin77 Good catch Doug, will update that, might have overlooked it.

**Comment by asaadmahmood** [comment]
@wiggin77 Just checked it out, and I think rgb(220, 220, 220), shouldn't have a yellow tint to it.
The yellow tint is coming because the text has an opacity to it, and the background has a yellow tint to it.
But that's fine. So we can take this.

Screenshot 2021-07-15 at 1 33 00 AM

**Comment by wiggin77** [comment]
> Just checked it out, and I think rgb(220, 220, 220), shouldn't have a yellow tint to it.

Yup - my mistake.  I typed 220 into a color picker for RGB, but the B component didn't update the color until I clicked away.  I was looking at 220/220/200

**Pull request merged**
