### PR TITLE
i18n: fix zh-cn & zh-tw default message mapping mistake

### PR DESCRIPTION
**Pull request by tianjuan**
#### Summary

zh-CN: Mainland China, simplified characters
zh-TW: Taiwan, traditional characters

https://en.wikipedia.org/wiki/Language_localisation

### CODE REVIEW

**Comment by jespino** [comment]
@tianjuan to accept the PR we need you to sign the CLA agreement.

**Comment by harshilsharma63** [comment]
@tianjuan would you be willing to sign the CLA?

**Comment by harshilsharma63** [comment]
@tianjuan I see you closed the PR. Is this no longer needed?

**Pull request closed without merging**
