### PR TITLE
Disable patches on unmount on readOnly mode

### LINKED ISSUE #4074: Bug:
Hi,

Since I downloaded and deployed the v7.4.2 focalboard, I noted when an issue with the txt block.

# Steps to reproduce the behaviour

1- Go to boards
2 - Select any board and navigate to table view
3 - Create a project with an txt column
4 - Write a comment
5 - Navigate to the board view
6- Navigate to the table view

# Expected behaviour

The txt comment disapear.

# IMG
2022-10-24 11_49_12-Suivi IT _ Avancements
2022-10-24 11_48_51-Suivi IT _ Suivi

# Edition and Platform

    Edition: Personal Server and docker
    Version: [v7.4.2]
    Browser and OS: [Windows and Firefox/Edge]

Tks for your help.
Thibaut

### LINKED ISSUE #4081: Bug: The value in Number Field disappear when we change a board view
## Steps to reproduce the behavior

1. Enter the Mattermost Boards and create issue 
2. Edit issue in boards view and fill the number type field
3. Close the edit screen and change a view to "table"

## Expected behavior

The number field must be filled after we change the board view 

## Screenshots (optional)

https://user-images.githubusercontent.com/109951790/197762365-441909dd-e1c2-44f0-ae3b-40f3a6ab2489.mp4

## Edition and Platform

 - Edition:Mattermost Boards (plugin)
 - Version: v7.4.3
 - Browser and OS: [Mac, Windows]

### PR DESCRIPTION
**Pull request by jespino**
#### Summary
Disable patches on unmount on readOnly mode

#### Ticket Link
Fixes #4081
Fixes #4074

### CODE REVIEW

**Comment by jespino** [comment]
@sbishel I think this should be cherry-picked to a dot release.

**Review by Pinjasaur — APPROVED** [review]
LGTM. Also handles #4074. I'll update the closing keywords.

Also tested for #4073 but that behavior remains. Seems to be related to editing property values in the table view (vs opening the table row into the card modal) not PATCHing.

**Comment by Pinjasaur** [comment]
@sbishel I'll get this merged into `main` now. I agree with Jesus that if we're able to, this would be an excellent candidate for a patch release too.

**Comment by Alderaaan** [comment]
Hi,
All values in txt field are ok for you ?
It's seem the lasrt upgrade fixed one but not the my second txt field.

Tks

**Comment by Pinjasaur** [comment]
Hey @Alderaaan, this PR hasn't been released yet. Have you been testing locally? If you're able to reproduce it from the latest `main` branch, can you post in #4074 and it can be reopened?

**Comment by Alderaaan** [comment]
Hi,
Yes I have testing with docker and the mattermost/focalboard:latest.
I will reproduce it and write it on post #4074.

**Comment by Pinjasaur** [comment]
@Alderaaan the `latest` tag is the _latest release_—the `edge` tag is the _latest build_ e.g. the `main` branch. I would make sure to try with `edge` since there hasn't been a release quite yet.

**Comment by Alderaaan** [comment]
@Pinjasaur , ok sorry, I tried with the main branch and it's working :)

**Pull request merged**
