### PR TITLE
Fixed a bug causing duplicate options to appear in board calculations

### LINKED ISSUE #1696: Bug: Board calculations menu shows repeated entries
## Steps to reproduce the behavior

1. Export the [Focalboard v1 team board](https://community-daily.mattermost.com/boards/workspace/qgsck6cts3fwpqwyjiupjm5cde/47aa9bb4-6967-4a96-83c7-11bd6b20f1eb/7e38eab4-890a-4fc3-8f48-a1f9bd1ab822) as an archive
2. Import it into a test server running v0.10.0 RC1
3. Open the "By Target release" view
4. Select a column summary calculation
5. Notice that the menu shows many repeated entries (for Sum, Avg, etc.)

## Expected behavior

Only one set of calculation functions at the top level.

## Screenshots

Screen Shot 2021-10-28 at 2 34 15 PM

Screen Shot 2021-10-28 at 2 41 51 PM

Screen Shot 2021-10-28 at 2 42 07 PM

## Edition and Platform

 - Edition: Mattermost plugin
 - Version: v0.10.0 RC1
 - Browser and OS: Chrome 93 on macOS

### PR DESCRIPTION
**Pull request by harshilsharma63**
#### Summary
Fixed a bug causing duplicate options to appear in board calculations

#### Ticket Link
Fixes #1696

### CODE REVIEW

**Comment by hahmadia** [comment]
Not related but choosing range, I got this. If possible to fix in this PR it be nice but just pointing it out
image

**Review by hahmadia — COMMENTED** [review]
Problem is fixed for same types but it is confusing when we have different types that have same calculation type. For example `Last Updated Time` and `Number` show range with seemingly different results? 

image

Thoughts? 

Notion differentiates it via a clear naming

image

**Comment by harshilsharma63** [comment]
@hahmadia I've updated date function names to indicate that they are for date fields.

**Comment by harshilsharma63** [comment]
> Not related but choosing range, I got this. If possible to fix in this PR it be nice but just pointing it out image

This is a 


> Not related but choosing range, I got this. If possible to fix in this PR it be nice but just pointing it out image

Created separate ticket for addressing this - https://community-daily.mattermost.com/boards/workspace/qgsck6cts3fwpqwyjiupjm5cde/47aa9bb4-6967-4a96-83c7-11bd6b20f1eb/ca1a5441-4c1c-4d0e-856e-88cc744576c8?c=b181533b-0205-4fc3-822b-3de4380bbc2b

**Review by hahmadia — APPROVED** [review]
Looks good. I think it's better to open the bug in Github so we can triage it.

**Comment by hahmadia** [comment]
Filed a github bug here https://github.com/mattermost/focalboard/issues/1721

**Pull request merged**
