### PR TITLE
fix: render default LHS board icon

### LINKED ISSUE #2958: UI: Align board text in the LHS and use a default icon as placeholder
## Steps to reproduce the behavior

1. Add multiple boards on the LHS
2. Some with icon, some with not
3. The starting point of the text is not aligned

## Expected behavior
- The starting point of the text should be vertically aligned
- And we can add a placeholder icon (boards) icon on the LHS instead of the custom one if it has no icon.

## Screenshots (optional)
Screenshot 2022-04-28 at 1 31 57 PM

## Edition and Platform
 - Edition: Mattermost Boards (plugin)
 - Version: v0.16.0
 - Browser and OS: Chrome on Mac

## Additional context (optional)
SEV3

### PR DESCRIPTION
**Pull request by Pinjasaur**
#### Summary

Fixes LHS board title alignment by rendering a default (`<BoardIcon>`) icon if there is not a custom one set.

image

#### Ticket Link

closes #2958

### CODE REVIEW

**Review by harshilsharma63 — APPROVED** [review]
LGTM 👍

**Comment by harshilsharma63** [comment]
@Pinjasaur can we add a test for this? Changes look good otherwise.

**Comment by Pinjasaur** [comment]
> @Pinjasaur can we add a test for this? Changes look good otherwise.

👍🏻 was thinking the same thing

**Review by jespino — APPROVED** [review]
LGTM

**Pull request merged**
