### PR TITLE
Disable patches on read-only unmount for url property

### PR DESCRIPTION
**Pull request by sbishel**
#### Summary
Disable patches on unmount on readOnly mode

#### Ticket Link
Fixes https://mattermost.atlassian.net/browse/MM-50951

### CODE REVIEW

**Comment by lindy65** [comment]
Hi @sbishel - in order to spin up a spinwick, do we need a corresponding PR on the server repro?

**Review by BenCookie95 — APPROVED** [review]

**Comment by sbishel** [comment]
> Hi @sbishel - in order to spin up a spinwick, do we need a corresponding PR on the server repro?

Yes. For now you do. I went ahead and created one...

https://github.com/mattermost/mattermost-server/pull/22409

**Review by lindy65 — APPROVED** [review]
Thanks @sbishel - tested URL properties as per [Jira ticket](https://mattermost.atlassian.net/browse/MM-50951) on [server PRs spinwick](https://github.com/mattermost/mattermost-server/pull/22409) and this issue is fixed. URL is retained in all different views.

**Review by mgdelacroix — APPROVED** [review]

**Pull request merged**
