### PR TITLE
GH-1907 - Updating person popover

### PR DESCRIPTION
**Pull request by asaadmahmood**
#### Summary
GH-1907 - Updating person popover

#### Ticket Link
https://github.com/mattermost/focalboard/issues/1907

#### Screenshot
Screenshot 2021-12-09 at 10 08 38 PM
Screenshot 2021-12-09 at 11 27 57 PM

### CODE REVIEW

**Review by sbishel — APPROVED** [review]
@asaadmahmood Do you know why the GUIDs are being displayed in the images? I downloaded and ran locally, I'm not seeing the GUIDs only names, so I assume it has something to do with your data but wanted to ask.

**Comment by asaadmahmood** [comment]
@sbishel You should have the images if you run it in plugin mode, as I think we always have images for users in Mattermost.

**Review by jespino — APPROVED** [review]
LGTM

**Comment by wuwinson** [comment]
@asaadmahmood Is this supposed to show the profile picture if a user has one uploaded? I tried on Scott's test server and only see the letter avatar even though I have profile pic. Also to confirm, this does not change the display of username to full name correct? cc @sbishel

**Comment by asaadmahmood** [comment]
@wuwinson Yes, it should work similar to Channels, channels shows the one named avatar, even if the user has not uploaded any avatar, we basically generate avatars for them.
And yes, this doesn't add the full name.

**Pull request merged**
