### PR TITLE
Stopped reacting to initial text changes and not being a controlled component

### LINKED ISSUE #4005: Bug: Cursor moves to the end of the text
## Steps to reproduce the behavior

1. Open a card
2. Start typing a comment
3. Move the cursor from the end of the text to somewhere in the middle
4. Start typing
5. Notice that after the first letter is entered, the cursor moves back to the end of the text

## Expected behavior

Cursor should not move

## Screenshots (optional)

https://user-images.githubusercontent.com/15314183/195405616-91988427-3a68-4758-a6b0-3db8d7fc10fa.mp4

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v7.4.2
 - Browser and OS: Chrome on Windows

### PR DESCRIPTION
**Pull request by harshilsharma63**
Fixes #4005

### CODE REVIEW

**Comment by harshilsharma63** [comment]
Will need to manually cherrypick due to mismatch in milestone and branch names this time.

**Comment by harshilsharma63** [comment]
@jespino for now I've only resolved the specific bug mentioned in the associated issue. I've not implemented the more enhanced design that we discussed over chat as it started to get complex beyond what's good for a patch release.

**Review by jespino — APPROVED** [review]
LGTM

**Pull request merged**
