### PR TITLE
 Fixed Incorrect icon in a board's 3-dot menu for "Hide board"

### PR DESCRIPTION
**Pull request by varghesejose2020**
Fixing Incorrect icon in a board's 3-dot menu for "Hide board"  #3978

### CODE REVIEW

**Review by Pinjasaur — CHANGES_REQUESTED** [review]
Hey @varghesejose2020, thanks for your contribution! ✨  Looks like some of the Jest snapshots need updating. To do so, run `npm run updatesnapshot` from the `webapp` directory please.

**Review by jespino — APPROVED** [review]
Everything looks good to me apart from the comment from @Pinjasaur, Thanks @varghesejose2020 :tada:

As soon as the snapshot tests are updated this will be ready to merge.

**Pull request closed without merging**
