### PR TITLE
GH-2502 - Fix Shared Boards

### PR DESCRIPTION
**Pull request by sbishel**
#### Summary
Updates necessary for Shared Boards to work with permission changes.

#### Ticket Link

  Fixes https://github.com/mattermost/focalboard/issues/2502

### CODE REVIEW

**Comment by harshilsharma63** [comment]
@sbishel I tried the steps in the linked issue and I'm always sent to this URL - `http://localhost:8000/error?id=not-logged-in`.

**Comment by sbishel** [comment]
@harshilsharma63 - I discovered when running locally, you need to make sure to build the webapp as well as the plugin. Locally, the `plugins/focalboard` path loads from the webapp, not the plugin. 

I updated my test server to this PR. You can test it out here - 
https://sbishel-test.test.mattermost.cloud/signup_user_complete/?id=gy8ukugpn3nzjdipp1cor81oro
or use normal sysadmin credentials.

**Comment by sbishel** [comment]
Opened - https://github.com/mattermost/focalboard/pull/2581 after permissions branch merge to main.

**Pull request closed without merging**
