### PR TITLE
Improve the board creation from channels

### LINKED ISSUE #3367: Feature Idea: Creating a board from the channel intro button should automatically link the board to the channel
## Summary

I think it makes sense that the board is automatically linked to the channel if created from the "Create a board" button in the channel.
Without that, the user has to go through the extra steps of linking it.

image

## How important this is to me and why

Importance: Medium

### PR DESCRIPTION
**Pull request by jespino**
Fixes #3367

### CODE REVIEW

**Review by sbishel — APPROVED** [review]

**Comment by sbishel** [comment]
I just noticed this is going directly to `release-7.2`, do we need this in `main` as well?

**Comment by jespino** [comment]
@sbishel yes, but main was broken for me because the multiproduct architecture and some dependency problems. It needs to be cherry picked to main

**Pull request merged**
