### PR TITLE
[feat] Notice.txt generation configuration

### PR DESCRIPTION
**Pull request by phoinixgrr**
#### Summary

Building on https://github.com/mattermost/mattermost-plugin-playbooks/pull/1255 we continue the effort to automate `notice.txt` generation for `focalboard` 

We selected `.config/notice-file` directory, to store the configuration files. Let us know if we need to relocate this. 

#### Ticket Link

Ticket: https://mattermost.atlassian.net/browse/CLD-3697

### CODE REVIEW

**Review by pfltdv — APPROVED** [review]
:100: LGTM

**Comment by Pinjasaur** [comment]
@wiggin77 any objections on your end? I ask because of your recent work for multi-product architecture and want to make sure these changes will be compatible 🙂

**Comment by wiggin77** [comment]
> @wiggin77 any objections on your end? I ask because of your recent work for multi-product architecture and want to make sure these changes will be compatible slightly_smiling_face

It doesn't look like this will conflict with the multi-product architecture changes.  That said, why use a hidden directory?  I'm not a fan of hidden directories that get checked in.

**Comment by phoinixgrr** [comment]
> > @wiggin77 any objections on your end? I ask because of your recent work for multi-product architecture and want to make sure these changes will be compatible slightly_smiling_face
> 
> It doesn't look like this will conflict with the multi-product architecture changes. That said, why use a hidden directory? I'm not a fan of hidden directories that get checked in.

We can easily change that. Let me know of the exact path that you would like this configuration to exist.

**Comment by wiggin77** [comment]
> Let me know of the exact path that you would like

Thanks @phoinixgrr.  Can the directory be called "notice" or "noticegen"?  I'm 0/5 on the actual name, as long as it's not a hidden directory.

**Comment by phoinixgrr** [comment]
> > Let me know of the exact path that you would like
> 
> Thanks @phoinixgrr. Can the directory be called "notice" or "noticegen"? I'm 0/5 on the actual name, as long as it's not a hidden directory.

The name is irrelevant to the functionality of the tool. It can be whatever you want 👍 

`noticegen/notice-file` 

Let me know if that works!

**Comment by wiggin77** [comment]
> The name is irrelevant to the functionality of the tool. It can be whatever you want +1
> 
> `noticegen/notice-file`

@phoinixgrr that works for me.  Thanks.

**Comment by phoinixgrr** [comment]
> > The name is irrelevant to the functionality of the tool. It can be whatever you want +1
> > `noticegen/notice-file`
> 
> @phoinixgrr that works for me. Thanks.

Rebased and force pushed changes.

**Review by wiggin77 — APPROVED** [review]
LGTM :+1:

**Comment by phoinixgrr** [comment]
@wiggin77 some tests failing. The changes introduced here, should not have caused this. 
Any ideas what may be going wrong?

**Pull request merged**
