### PR TITLE
Added property to select multiperson

### PR DESCRIPTION
**Pull request by Rajat-Dabade**
#### Summary
This PR will add the property to select multiple persons.

### CODE REVIEW

**Review by sbishel — APPROVED** [review]
When testing, the person list did not change when making the board public. It still only displayed the explicit team members. (I thought an "open" board should display all members of that team.) However, this was true for the original "person" property as well, so it may be a separate bug. I would just investigate and make sure before merging. If so, create another ticket for that issue.

**Review by jespino — APPROVED** [review]
LGTM

**Pull request merged**
