### PR TITLE
Doc: Update index.md

### PR DESCRIPTION
**Pull request by varghesejose2020**
#### Summary

Fix: Community channel Link

### CODE REVIEW

**Review by wuwinson — APPROVED** [review]
Looks good, thanks @varghesejose2020!

**Comment by chenilim** [comment]
Looks like a minor doc update. @justinegeffen, could you help double-check and update the website? Thanks.

**Review by justinegeffen — APPROVED** [review]

**Comment by justinegeffen** [comment]
@chenilim, just a ping on this for visibility. :)

**Comment by chenilim** [comment]
@justinegeffen, just double checking that you are going to merge this and update the website right? LMK if you need help. Thanks.

**Comment by chenilim** [comment]
Website updated, and invalidation created (Cmd+Shift+R to force refresh if needed). Also cc @emdecr.

**Pull request merged**
