### PR TITLE
fixed typo in modal

### PR DESCRIPTION
**Pull request by shikhar13012001**
Fixed typo in modal in `en.json` and `confirmAddUserForNotifications.tsx`
#### Ticket Link

 Fixes https://github.com/mattermost/focalboard/issues/3940

### CODE REVIEW

**Review by sbishel — APPROVED** [review]

**Comment by sbishel** [comment]
@shikhar13012001 - thanks for your contribution, looks like a snapshots needs updated.  Then ping me to review and we'll get it merged.

**Comment by shikhar13012001** [comment]
hi @sbishel, thanks for the review, can you please guide me, on how to update snapshots?

**Comment by sbishel** [comment]
> hi @sbishel, thanks for the review, can you please guide me, on how to update snapshots?

simply run `npm test -- -u` from the `webapp` directory.

**Comment by shikhar13012001** [comment]
Hi @sbishel  , sorry to bother again but I am getting this error on my machine, after 
```bash
cd webapp
npm install
```
image

Can you help me with this ?

**Comment by shikhar13012001** [comment]
Hi @sbishel , I ran the command `npm test -- -u` and I see one test fail.
image

**Comment by sbishel** [comment]
@shikhar13012001 - Thanks for your contribution.

**Pull request merged**
