### PR TITLE
[GH-2965] Don't close property selector menu when item is clicked

### PR DESCRIPTION
**Pull request by kamre**
#### Summary
Property selector menu is not closed when some property is selected or deselected:
- applied to menus in `ViewHeaderPropertiesMenu` and `FilterValue` components
- new property `suppressItemClicked` added to `SwitchOption` component to avoid dispatching `menuItemClicked` event
- unit tests and jest snapshots updated
- cypress tests updated
- new unit tests for checking that menu is not closed added

Here is how it looks for properties menu:

and for filtering value:

#### Ticket Link
Fixes: #2965 and #3361

### CODE REVIEW

**Comment by kamre** [comment]
Hi @chenilim @harshilsharma63 , please review the changes.

**Comment by harshilsharma63** [comment]
@kamre any way to make the changes not update so many snapshots? If they absolutely must, can you please describe why so?

**Comment by kamre** [comment]
@harshilsharma63 almost all snapshot differences come from this change in the `MenuWrapper` component:
image
 As you can see on the right side I needed additional wrapper for the button that activates the menu. This was required because otherwise any clicks from the menu with items will lead to `toggle` call and close the menu.

But this was before I have added `stopPropagation` call to every clickable menu item. So I will check if this wrapper is still needed.

**Comment by kamre** [comment]
@harshilsharma63 The changes to `MenuWrapper` structure are not needed. So I have reverted them and now the diff is really small. Please review.

**Review by harshilsharma63 — APPROVED** [review]

**Comment by harshilsharma63** [comment]
LGTM 👍

**Pull request merged**
