### PR TITLE
Fixes issue with dates and daylight savings

### PR DESCRIPTION
**Pull request by sbishel**
#### Summary

Found issue because unit tests began to fail. The TimeZoneOffset was being determined based on today. If the date being saved or retrieved is on the other side of the Daylight Savings time change, the hour would be off by 1.

Does not really affect current users because we don't save time, but could in the future.

### CODE REVIEW

**Review by jespino — APPROVED** [review]
LGTM

**Review by mgdelacroix — APPROVED** [review]
LGTM! :+1:

**Comment by mgdelacroix** [comment]
There is a test still failing but looks unrelated and is failing on `main` as well

**Comment by sbishel** [comment]
I'm investigating the main failure, now.

**Pull request merged**
