### PR TITLE
CalendarView Remove Feature flag

### PR DESCRIPTION
**Pull request by sbishel**
#### Summary
Removes feature flag from calendar view allowing it to be available for on premise

#### Ticket Link
https://community.mattermost.com/boards/workspace/qgsck6cts3fwpqwyjiupjm5cde/47aa9bb4-6967-4a96-83c7-11bd6b20f1eb/7e38eab4-890a-4fc3-8f48-a1f9bd1ab822/69c78fb5-161c-4071-8bf3-e38d3fe6ecca

### CODE REVIEW

**Comment by wiggin77** [comment]
@sbishel, the `clientConfig` declaration needs to be removed.

**Comment by sbishel** [comment]
> @sbishel, the `clientConfig` declaration needs to be removed.

Thanks, @wiggin77

**Review by harshilsharma63 — APPROVED** [review]
LGTM!

**Review by ogi-m — APPROVED** [review]
LGTM

**Pull request merged**
