### PR TITLE
GH-2692 - Fix archive import

### PR DESCRIPTION
**Pull request by wiggin77**
#### Summary
Archive import was broken after permissions branch merge.
- API route was incorrect
- user was not added to the newly created boards

#### Ticket Link
fixes https://github.com/mattermost/focalboard/issues/2692
fixes https://github.com/mattermost/focalboard/issues/2629

### CODE REVIEW

**Review by sbishel — COMMENTED** [review]
LGTM

**Review by sbishel — COMMENTED** [review]
LGTM

**Comment by wiggin77** [comment]
@sbishel I think you commented but didn't approve.

**Review by sbishel — APPROVED** [review]
Sorrry

**Pull request merged**
