### PR TITLE
[MM-49159] Fix status dropdown menu avatar on click

### PR DESCRIPTION
**Pull request by kostaspt**
#### Summary
Removed the code reverting the position and excluded the status dropdown menu altogether as it's the only `.Menu` that could be affected inside `.focalboard-body`, but also the only selectors targeting `.Menu` globally in general. This may be due to a recent unrelated change, but the dropdown works as expected without the boards' plugin loaded, so it looks like this is affecting it.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-49159

### CODE REVIEW

**Comment by sbishel** [comment]
@asaadmahmood - Please review...

**Review by mkraft — APPROVED** [review]

**Review by asaadmahmood — APPROVED** [review]
LGTM

**Review by furqanmlk — APPROVED** [review]
Thanks @kostaspt for helping focalboard setup


https://user-images.githubusercontent.com/6909890/214879712-05d2366f-6108-4189-92f1-f46bc39ddacf.mp4

**Comment by amyblais** [comment]
@sbishel Is this ok to merge and to be included in v7.8?

**Comment by sbishel** [comment]
LGTM.

**Pull request merged**
