### PR TITLE
Store current input while user is changing.

### PR DESCRIPTION
**Pull request by sbishel**
#### Summary
Receives callback to store current input as user types. Uses this value when saving a type change, in case the property name change hasn't occurred.

#### Ticket Link

  Fixes https://github.com/mattermost/focalboard/issues/3059

### CODE REVIEW

**Review by jespino — CHANGES_REQUESTED** [review]
I'm having doubts about it, is there any reason to not do it in more normal way. for example, we can change the `onValueChanged` property to `onConfirmValue` or something like that, and create a new `onValueChanged` that is triggered with the `setValue` in the input's `onChange`, that way this is more a self contained component and you don't need to do weird ref stuff.

**Comment by sbishel** [comment]
> I'm having doubts about it, is there any reason to not do it in more normal way. for example, we can change the `onValueChanged` property to `onConfirmValue` or something like that, and create a new `onValueChanged` that is triggered with the `setValue` in the input's `onChange`, that way this is more a self contained component and you don't need to do weird ref stuff.

Updated based on your suggestion, much cleaner....

**Review by jespino — APPROVED** [review]
LGTM

**Pull request merged**
