### PR TITLE
GH-1024 - Updating table row css

### PR DESCRIPTION
**Pull request by asaadmahmood**
#### Summary
GH-1024 - Updating table row css

#### Ticket Link
https://github.com/asaadmahmood/focalboard/compare/GH-1024?expand=1

### CODE REVIEW

**Review by wiggin77 — APPROVED** [review]

**Comment by sbishel** [comment]
@ogi-m Will this affect rainforest?

**Comment by ogi-m** [comment]
@sbishel It shouldn't. I don't think we have any table view tests in RF yet, but I'll give a heads up to Lindy just in case.

**Comment by sbishel** [comment]
The cherry-pick did succeed. Not sure about the error.

**Comment by sbishel** [comment]
Ah...I didn't notice, this was merged directly into `release-0.10`. So I created another PR for `main`. 
https://github.com/mattermost/focalboard/pull/1793

**Pull request merged**
