### PR TITLE
GH-1916 - Set to first date field when loading

### PR DESCRIPTION
**Pull request by sbishel**
#### Summary
If the display is null, set to first date property.
Previously, after deleting the date property the createDate would be taken as default.

This follows the same pattern as is used for the groupByProperty.

There are some issues with this implementation, which another [issue](https://github.com/mattermost/focalboard/issues/2007) has been created to handle these issues.

#### Ticket Link
  Fixes https://github.com/mattermost/focalboard/issues/1916

### CODE REVIEW

**Review by wiggin77 — APPROVED** [review]
LGTM :+1:

**Review by harshilsharma63 — APPROVED** [review]
LGTM!

**Pull request merged**
