### PR TITLE
Moving the history instance creation after the plugin initialization (to honor the SiteURL config)

### LINKED ISSUE #1766: Boards not respecting Site URL
## Steps to reproduce the behavior
1. Setup Mattermost with Focalboard behind a reverse proxy forwarding through a prefix (https://site.com/mattermost).
2. Go to Boards (URL changes to https://site.com/boards/welcome while still working).
3. Refresh the page.
4. See 404.

## Expected behavior
URL stays beyond https://site.com/mattermost (as defined via Site URL).

## Edition and Platform
 - Edition: Mattermost Server / Focalboard
 - Version: v6.0.3-rc1 / v0.9.4
 - Browser and OS: any

### LINKED ISSUE #2032: Bug: Boards removes folder from SiteUrl causes 404 Error
## Steps to reproduce the behavior

1. Setup a Mattermost 6.2.1 instance in a folder on a domain e.g. Siteurl - https://iosteam.in/mattermost
2. Create a channel and a board for the channel
3. Go to the channel and then go to the board
4. Boards first goes to an url https://iosteam.in/mattermost/boards/workspace/1a5miyk8z3bnuj9ke184inc7kw
5. But then it redirects to another url https://iosteam.in/boards/workspace/1a5miyk8z3bnuj9ke184inc7kw/bt8ypsd9oo7bpibzcazt3you79o/v17t98d9ejpdujn77x7jrjw1fgr [incorrect site url]
6. Please note the folder in the Siteurl "mattermost" has been removed from the url in point number 5
7. Now if we refresh the page it causes a 404 error

## Expected behavior

The url in point number 5 above should have instead redirected to https://iosteam.in/mattermost/boards/workspace/1a5miyk8z3bnuj9ke184inc7kw/bt8ypsd9oo7bpibzcazt3you79o/v17t98d9ejpdujn77x7jrjw1fgr i.e. the same url with the folder name in the Siteurl "mattermost", this works fine.

## Screenshots

Please see the screen capture recording of the same.
https://user-images.githubusercontent.com/33347166/147927688-79574185-ad6f-4faf-9b2a-a056d2e7434b.mp4 

## Edition and Platform

 - Edition: Enterprise Edition Starter - Self Hosted
 - Version: 6.2.1
 - Browser and OS: [Firefox on Windows]

### PR DESCRIPTION
**Pull request by jespino**
Fixes #1766
Fixes #2032

This fixes the problem, but doesn't sorted out the multiple ways of getting the URLs.

### CODE REVIEW

**Comment by chenilim** [comment]
cc @ogi-m.

**Review by wiggin77 — APPROVED** [review]
LGTM :+1:

**Review by sbishel — APPROVED** [review]
LGTM and will also fix https://github.com/mattermost/focalboard/issues/1804 which I think is also a subpath issue.

**Comment by sbishel** [comment]
@chenilim @wuwinson We should consider this for a dot release for the focalboard plugin, which is why I added 0.12 as milestone.

**Comment by chenilim** [comment]
Yes, I agree we should schedule this for a dot release for 0.12 / Mattermost 6.3.x.

**Comment by sbishel** [comment]
@jespino Could you look at the cypress error? We would like to take this for 0.12.1

**Comment by jespino** [comment]
@sbishel I'm still working on fixing certaing bugs that @ogi-m found.

**Review by ogi-m — APPROVED** [review]
Everything looks good now, thanks @jespino !

**Pull request merged**
