### PR TITLE
changed from HTML button to Button component

### PR DESCRIPTION
**Pull request by Rishabhraghwendra18**
#### Summary

Changed from HTML button in `welcomePage.tsx` file with Button component
#### Issue
Issue: #1432

### CODE REVIEW

**Review by asaadmahmood — APPROVED** [review]

**Review by hahmadia — CHANGES_REQUESTED** [review]
Hi @Rishabhraghwendra18 ,

As Asaad has mentioned, the Button component uses different props. 

You can review the component file at `webapp/src/widgets/buttons/button.tsx`. Ensure you are passing through the correct props and ensure the appearance is the same as it was pre-component switch. 

Once you've completed that, feel free to tag me or request a re-review by clicking on the following icon. 
image

Thanks!

PS. Make sure you sign the CLA form so that we can have the ability to merge your PR after reviews! You can find the CLA at https://mattermost.org/mattermost-contributor-agreement/

**Comment by Rishabhraghwendra18** [comment]
Hi @hahmadia . I am setting up my environment as stated [here](https://github.com/mattermost/focalboard#building-and-running-standalone-desktop-apps)  for my ubuntu machine . But when I run `linux/dist/focalboard-app` in the root directory it's showing me this error: `zsh: no such file or directory: linux/dist/focalboard-app` . It is not able to find the dist folder . May you guide me which command I have to run to make this dist folder ?

**Comment by Rishabhraghwendra18** [comment]
> > Hi @hahmadia . I am setting up my environment as stated [here](https://github.com/mattermost/focalboard#building-and-running-standalone-desktop-apps)  for my ubuntu machine . But when I run `linux/dist/focalboard-app` in the root directory it's showing me this error: `zsh: no such file or directory: linux/dist/focalboard-app` . It is not able to find the dist folder . May you guide me which command I have to run to make this dist folder ?
> 
> @Rishabhraghwendra18 Can you try running "make prebuild" first and then retry the steps?

I tried this before command in the root directory then applied rest of the commands . Do I have to run this command in linux folder ?

**Comment by hahmadia** [comment]
Hi! I'll be closing this PR for now and putting the issue up for grabs. If you feel like you would like to give it another go, you can feel free to re-take the issue (if not already taken) and submit a new fix. Thank you for your understanding.

**Pull request closed without merging**
