### PR TITLE
go.mod: update mattermost-server dependency

### PR DESCRIPTION
**Pull request by isacikgoz**
#### Summary
After https://github.com/mattermost/mattermost-server/pull/21853 merged, we need to update the server dependency.

### CODE REVIEW

**Comment by wiggin77** [comment]
Thanks @isacikgoz 
/linux/go.mod need to be updated as well.

**Comment by agnivade** [comment]
Why do we need this? It should already be taken care of by go.work.

**Comment by isacikgoz** [comment]
> Why do we need this? It should already be taken care of by go.work.

We are not mandating mattermost-server to be present while developing focalboard hence I thought we still need to handle this dependency updates. I mean in the MPA workflow this is not required but for standalone and plugin development it may still be required. At least to silence build errors.

**Comment by agnivade** [comment]
Yes, for plugin development it's required. But the changes you made are only exclusively required in MPA mode correct?

**Comment by isacikgoz** [comment]
Sure the previous PRs were exclusive for MPA, but you still get editor errors while even if you don't working on the MPA.

**Comment by agnivade** [comment]
Clarified offline. Good to go :+1:

**Review by wiggin77 — APPROVED** [review]
LGTM :+1:

**Pull request merged**
