### PR TITLE
Adds escaping when normalizing table names for MySQL on DB helpers

### PR DESCRIPTION
**Pull request by mgdelacroix**
#### Summary
This PR adds escaping to the MySQL tables when using database helpers to allow admins to use schema names that start with a digit or in general require to be escaped.

#### Ticket Link
Fixes https://github.com/mattermost/focalboard/issues/4631

### CODE REVIEW

**Review by wiggin77 — APPROVED** [review]
LGTM :+1:

**Review by sbishel — APPROVED** [review]

**Comment by sbishel** [comment]
@mgdelacroix - should this go to `v7.8` as well, since its an ESR?

**Comment by mgdelacroix** [comment]
@sbishel agree, I'll cherry pick there as well

**Comment by mgdelacroix** [comment]
CI is failing due the mono-repo changes that are now applied in `mattermost-server` `master`. Merging not to block the cherry picks, but we should decide if we're going to fix the CI for this repo's `main` branch

**Comment by mgdelacroix** [comment]
Fix for the CI in `main` here https://github.com/mattermost/focalboard/pull/4669

**Pull request merged**
