### PR TITLE
Sidebar horizontal scrollbar fix

### PR DESCRIPTION
**Pull request by rohit1101**
Revert changes in package-lock.json

### CODE REVIEW

**Comment by rohit1101** [comment]
@jespino Even in this PR I reverted the changes in package-lock.json.

**Comment by jespino** [comment]
I think this was already handled in the other PR, right?

**Comment by rohit1101** [comment]
Oops sorry my bad!

Thank you for your support and guidance @jespino 

But I have a question to ask you why did my package-lock.json change when I forked and worked on my local machine ?

**Comment by jespino** [comment]
this can be slightly different or drastically different depending on the version of node/npm that you use, we use node 16, and that includes a new lock format.

**Comment by rohit1101** [comment]
Thanks for the quick response and support @jespino !!

Made my first open source contribution (which involved writing code)

**Comment by jespino** [comment]
@rohit1101 Glad to hear that! really amazing feeling! I hope is the first one of a lot of them! :confetti_ball:

**Pull request closed without merging**
