### PR TITLE
Remove timeout from MySQL migrations

### PR DESCRIPTION
**Pull request by mgdelacroix**
#### Summary
This PR reuses the server mechanism to remove the MySQL timeout from the connection string to bypass timeouts when running migrations.

A couple of follow up PRs will come later making the server method public for it to be used in Focalboard instead of duplicating the implementation.

#### Ticket Link
Fixes https://github.com/mattermost/focalboard/issues/2946

### CODE REVIEW

**Review by sbishel — APPROVED** [review]
Woohoo...Couple questions. This only affects mySQL? Do we need to worry about timeouts on large Postgres DBs? And it make sense, but just want to make sure...only ReadTimeOut is an issue. Thanks Miguel.

**Comment by mgdelacroix** [comment]
Only ReadTimeouts should be an issue as WriteTimeouts controls the time when the server is writing to the client. In any case, I tested the fix with both timeouts below migration time and it worked fine. As per postgres, I've tested migrations above the timeout set in the connection string and it seems to respect `morph`s timeout, so we're good only making changes to MySQL

**Comment by mgdelacroix** [comment]
@sbishel ^

**Comment by mgdelacroix** [comment]
After digging a bit deeper, the `connect_timeout` of Postgres only measures the time until the connection is established, but not the time it takes to run the queries. It has `statement_timeout`, which I've tested and can break migrations, but it's not set in our default parameters and it's default value is 0, which disables the timeout. Is as well [recommended not to be set globally in the official docs](https://www.postgresql.org/docs/current/runtime-config-client.html), so an admin would need to explicitly add it to the server connection string for it to cause problems.

I'd propose to follow what server is doing and assume `statement_timeout` is not set, and we can go back to it later if needed.

**Pull request merged**
