### PR TITLE
Trying to parallize tests

### PR DESCRIPTION
**Pull request by jespino**

### CODE REVIEW

**Comment by wiggin77** [comment]
I think it is running push and pull-request workflows.  Is that double the work?

**Comment by jespino** [comment]
@wiggin77 I guess so, but you changed it. I don't know if you want to polish that too.

**Comment by wiggin77** [comment]
> @wiggin77 I guess so, but you changed it. I don't know if you want to polish that too.

I think the matrix stuff is now causing both push and pull-request to run.  It wasn't doing that before.

**Comment by wiggin77** [comment]
Looking at the timings recorded, this does appear to be faster.

**Review by wiggin77 — APPROVED** [review]

**Pull request merged**
