### PR TITLE
Fixed a bug where mentions don't show up in descripotions

### LINKED ISSUE #2097: Bug: users don't display when typing "@" in description field.
## Steps to reproduce the behavior

1. Create multiple users in your installation.
2. Go to Description field of a card
3. Type "@"
4. No users are displayed

## Expected behavior

A popup of users should appear.

## Edition and Platform

 - Edition: Mattermost plugin
 - Version: [v0.12.0 - tip]
 - Browser and OS: [Chrome 96 on macOS]

## Additional context

I have narrowed it down to this section 
https://github.com/mattermost/focalboard/blob/release-0.12/webapp/src/components/markdownEditorInput/markdownEditorInput.tsx#L59-L62

If this is commented out, the @mentions works correctly. But then this bug is back. 
https://github.com/mattermost/focalboard/issues/2036

### PR DESCRIPTION
**Pull request by harshilsharma63**
#### Summary
Fixed a bug where mentions don't show up in descripotions

#### Ticket Link
Fixes #2097

### CODE REVIEW

**Review by jespino — APPROVED** [review]
LGTM

**Comment by harshilsharma63** [comment]
@ogi-m can you please test this before I merge in main and cherrypick for 0.12?

**Comment by ogi-m** [comment]
@harshilsharma63 LGTM, at-mentions are working and verified that https://github.com/mattermost/focalboard/issues/2036 is also working as expected

**Comment by harshilsharma63** [comment]
Merged in `main` and cherrypicked in `release-0.12`.

**Pull request merged**
