### PR TITLE
Fix message

### PR DESCRIPTION
**Pull request by kaakaa**
#### Summary
I think that `the property` in the message doesn't mean anything. Existing message may just be copied from https://github.com/mattermost/focalboard/blob/main/webapp/src/components/cardDetail/cardDetailProperties.tsx#L102.

#### Ticket Link
N/A

### CODE REVIEW

**Comment by sbishel** [comment]
Thanks. @kaakaa - Please run `npm run i18n-extract` to update the en.json file.

**Comment by kaakaa** [comment]
@sbishel Oh sorry, I missed it. Updating `en.json` was done.

**Review by sbishel — APPROVED** [review]
Thanks @kaakaa

**Pull request merged**
