### PR TITLE
[GH-1581] fix menu widget

### LINKED ISSUE #1581: Bug: submenus are always visible
1. Click on _Settings_ menu
2. Hover over _Set theme_ to show submenu
3. Move mouse to _Random icons_ menu item
4. Submenu is still visible

## Expected behavior

Submenu should disappear when any other menu item on the same level is hovered.

## Screenshots
SubmenuAlwaysVisible

## Edition and Platform

 - Edition: Personal Desktop / Personal Server
 - Version: `main` branch
 - Browser and OS: Chrome 94 on Windows 10

## Additional context
Regression was introduced in this pull request:
- #1553

@adithyaakrishna FYI

### PR DESCRIPTION
**Pull request by jrester**
#### Summary

In #1553 the `onMouseLeave` callback was removed which lead to the settings sub menus not closing properly. This PR adds a flag to close a submenu on mouse leave. 

#### Ticket Link

Fixes #1581

### CODE REVIEW

**Comment by emilyacook** [comment]
Thanks for participating in Hacktoberfest! You can claim your sticker set here: https://get.printfection.com/hacktober21/4144583267 @jrester

**Comment by jrester** [comment]
@kamre could you take a look

**Comment by kamre** [comment]
@jrester I am not a core developer so my word is definitely not final one.

Regarding the changes: implementation seems to work correctly and that is really nice.

But may be it will be better to introduce `React.Context` for menu so that there will be no need to wrap menu options with additional `div` and just create a custom hook like `useMenuContext` that will provide all required props for different menu options. I have done [something similar with card details](https://github.com/mattermost/focalboard/blob/f74eea11ba43624b38c7a9a27f3722465ac909b1/webapp/src/components/cardDetail/cardDetailContext.tsx#L24) when different elements from the card need to coordinate their behaviour.

**Comment by chenilim** [comment]
@jespino, please merge if there are no outstanding issues. Thanks.

**Comment by chenilim** [comment]
@sbishel, can we merge this unless there are remaining issues? The menu bug is something we want to fix soon (easy to hit this constantly, even though a sev 3). cc @wuwinson.

**Comment by sbishel** [comment]
Just some conflicts that need fixed. @jrester - Would you be able to sync and resolve conflicts. Otherwise I can take a shot at it.

**Comment by sbishel** [comment]
Update and merged in this PR - https://github.com/mattermost/focalboard/pull/2509

**Pull request closed without merging**
