### PR TITLE
Update en.json: Bug fix and consistency

### PR DESCRIPTION
**Pull request by justinegeffen**
Updated copy and fixed https://github.com/mattermost/focalboard/issues/3131
Copy changes are primarily casing (uppercase to lowercase) for consistency. Minor punctuation changes ("read only" to read-only). One bug fix.

### CODE REVIEW

**Review by wiggin77 — APPROVED** [review]
LGTM :+1:

**Review by chenilim — APPROVED** [review]
LGTM! I believe you should be able to merge this after CI passes @justinegeffen, but LMK if you need me or Doug to merge it. Also FYI @wuwinson and @asaadmahmood.

**Comment by sbishel** [comment]
This thing exploded, although all string changes. This needs to be ported to main as well.

**Review by wiggin77 — APPROVED** [review]
LGTM :+1:   Yay for Oxford Comma.

**Comment by justinegeffen** [comment]
Thanks, @sbishel and @wiggin77! Apologies if I broke anything! Thanks for merging. :)

**Pull request merged**
