### PR TITLE
Revert dnd

### PR DESCRIPTION
**Pull request by mgdelacroix**
#### Summary
This PR reverts the updates to the DND on the LHS. It reverts, in order, e075f40, 7db7e56 and 9918a0b, and makes the appropriate fixes.

The revert takes away migrations 30, 31 and 32, which are suspected to be causing performance issues.

### CODE REVIEW

**Review by sbishel — APPROVED** [review]
Thanks @mgdelacroix I think this will need cp'ed to release-7.6 as well.

**Comment by wiggin77** [comment]
> Thanks @mgdelacroix I think this will need cp'ed to release-7.6 as well.

I'll do the CP as it's getting late for mgdelacroix.

**Review by wiggin77 — APPROVED** [review]
LGTM :+1:

**Comment by wiggin77** [comment]
Cherry-pick to release-7.6 is here:  https://github.com/mattermost/focalboard/pull/4295

**Pull request merged**
