### PR TITLE
[GH-1130] Fixes 'Today' button not selecting date and entered date not being selected in calendar

### PR DESCRIPTION
**Pull request by CuriousCorrelation**
#### Summary

1. Fixes 'Today' button not selecting date in the calendar and updating the value.
2. Fixes entered date in `DayPickerInput` not being selected in the calendar.

#### Ticket Link

Fixes https://github.com/mattermost/focalboard/issues/1130

### CODE REVIEW

**Comment by harshilsharma63** [comment]
@CuriousCorrelation would you be willing to add some tests for this?

**Comment by CuriousCorrelation** [comment]
@harshilsharma63 Sure! I'll get to it shortly

**Comment by harshilsharma63** [comment]
Awesome, Thanks!

**Review by harshilsharma63 — CHANGES_REQUESTED** [review]
Let's add some tests for this.

**Review by harshilsharma63 — APPROVED** [review]
LGTM!

**Pull request merged**
