### PR TITLE
Backport GetBoardMetadata()

### PR DESCRIPTION
**Pull request by sbishel**
#### Summary
Backport of https://github.com/mattermost/focalboard/pull/2569 to release-7.0.

#### Ticket Link

  Fixes https://github.com/mattermost/focalboard/issues/3042

### CODE REVIEW

**Review by Pinjasaur — APPROVED** [review]
LGTM

**Comment by sbishel** [comment]
@chenilim - I would like you take a look at this backport, since you wrote the original PR. Thanks

**Review by chenilim — APPROVED** [review]
I'm not sure if bindata.go should be updated (there are no migration changes with this API), but otherwise, the port LGTM. I ran the tests a few more times.

**Comment by sbishel** [comment]
> I'm not sure if bindata.go should be updated (there are no migration changes with this API), but otherwise, the port LGTM. I ran the tests a few more times.

Reverted bindata. Nice catch

**Pull request merged**
