### PR TITLE
Gh-2437 - Updating share board modal

### LINKED ISSUE #2519: Bug: Long URL in comment makes Send button go off the screen
## Steps to reproduce the behavior

1. Open a card
2. Paste in a long, unbroken URL, e.g. `https://www.loom.com/share/kwjfkafskhdfkahdfksdkfqgwiurgui4r974yriu3qy4rui4iuh3qiufhwrhfkwhfkhrksdfksfksdfkskhdfghagfkasfgkja`
3. Send button goes out of view

## Expected behavior

Send button stays in view

## Screenshots

https://user-images.githubusercontent.com/46905241/157744243-7e220209-6420-4116-ba85-221ee1a346f9.mov

## Edition and Platform

 - Edition: Mattermost plugin
 - Version: v0.15 RC1
 - Browser and OS: Chrome on Mac

## Additional context

May be related to https://github.com/mattermost/focalboard/issues/2456?

### PR DESCRIPTION
**Pull request by asaadmahmood**
#### Summary
Gh-2437 - Updating share board modal

#### Ticket Link
Fixes https://github.com/mattermost/focalboard/issues/2437
Fixes #2519

### CODE REVIEW

**Review by sbishel — APPROVED** [review]
LGTM - Tested and working as expected.

**Review by wuwinson — APPROVED** [review]
LGTM!

**Comment by sbishel** [comment]
@asaadmahmood - Can you check on the failing test?

**Comment by asaadmahmood** [comment]
Done @sbishel

**Pull request merged**
