### PR TITLE
MM-58570 - Removing create a board button

### PR DESCRIPTION
**Pull request by asaadmahmood**
#### Summary
MM-58570 - Removing create a board button
Removed the button as we are no longer driving adoption to boards.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-58570
https://mattermost.atlassian.net/browse/MM-58181

#### Screenshots
CleanShot 2024-07-15 at 22 26 32@2x

### CODE REVIEW

**Review by mgdelacroix — APPROVED** [review]
LGTM! :+1:

**Comment by harshilsharma63** [comment]
I believe we'll only be creating new plugin release from the other repo instead - https://github.com/mattermost/mattermost-plugin-boards right @marianunez @Rajat-Dabade ? If so, I suggest we port this PR to the other repo and close this PR. Even the CI is broken in here.

**Comment by Rajat-Dabade** [comment]
@harshilsharma63, Yup we should port this PR to the new Repo.

**Comment by asaadmahmood** [comment]
Sounds good @harshilsharma63 will close it and submit one there.

**Pull request closed without merging**
