### PR TITLE
GH-1864 Add + sign to add new event.

### PR DESCRIPTION
**Pull request by sbishel**
#### Summary
Added + to anchor tag in order to allow creating a new card via the "+" button. 

Still allows drag and drop to create multiple date cards. 

#### Ticket Link
https://github.com/mattermost/focalboard/issues/1864

#### Screen Shot
Screen Shot 2021-11-29 at 5 32 32 PM

Screen Shot 2021-11-29 at 5 34 29 PM

Uploaded to test server -
https://sbishel.test.mattermost.cloud/signup_user_complete/?id=pmr8gg9kobfu8g7wtwrmenrngc

### CODE REVIEW

**Comment by sbishel** [comment]
@asaadmahmood - May need some css tweeks...

**Comment by wuwinson** [comment]
@asaadmahmood @sbishel Functionality-wise, this works great! A few UX things to consider:

1. Button is small and requires precision to click. A bigger button would be helpful.
2. The 'x' button on the top left of a card makes it feel more like a cancel rather than a close. When I click on the '+' to create a card, then click on the 'x' on the top left, I wasn't expecting a card to get created. Since this is not specific to calendar view, can we maybe rename the button to "Close" for the time-being and evaluate how we want to handle the cancel/close action in the future?

**Review by harshilsharma63 — APPROVED** [review]
LGTM!

**Review by asaadmahmood — APPROVED** [review]
LGTM after my changes.

**Pull request merged**
