### PR TITLE
GH-2447 - Updating label overflow

### PR DESCRIPTION
**Pull request by asaadmahmood**
#### Summary
GH-2447 - Updating label overflow

#### Ticket Link
Fixes https://github.com/mattermost/focalboard/issues/2447

### CODE REVIEW

**Review by chenilim — APPROVED** [review]
Sorry  I missed this. LGTM! You shouldn't need PM review for this though.

**Comment by wuwinson** [comment]
@asaadmahmood @sbishel @harshilsharma63 @chenilim Still seeing the issue on Chrome 96 on macOS:
https://user-images.githubusercontent.com/93531870/157545069-ce09e401-8464-4351-882c-f5248583910d.mov

**Comment by wuwinson** [comment]
@asaadmahmood @sbishel @harshilsharma63 @chenilim Still seeing the issue on Chrome 96 on macOS:
https://user-images.githubusercontent.com/93531870/157545069-ce09e401-8464-4351-882c-f5248583910d.mov

**Comment by harshilsharma63** [comment]
Hi @asaadmahmood The primary issue is fixed but the overall experience with long property values is still not great. Check out this loom here - https://www.loom.com/share/bd5770e5439948e7a2ef2ddca104ea9d

We can delay this with permissions feature release if that's better. This isn't a new bug and is an edge case.

**Comment by asaadmahmood** [comment]
@harshilsharma63 I'll fix this.

**Comment by sbishel** [comment]
@wuwinson - Please retest...

**Review by wuwinson — APPROVED** [review]
LGTM!

**Pull request merged**
