### PR TITLE
Adds a check that errors on store start if MariaDB is detected

### PR DESCRIPTION
**Pull request by mgdelacroix**
#### Summary
These changes causes the app to error on start if the database is detected to be MariaDB

### CODE REVIEW

**Comment by wiggin77** [comment]
@mgdelacroix this feels like we're telling customers MariaDB is officially dropped as an unofficially supported database.  In other words, we're saying if you're on MariaDB you can't use Mattermost going forward.  Is that really what we want?

**Comment by sbishel** [comment]
We already say that here - https://docs.mattermost.com/install/software-hardware-requirements.html#database-software

> MariaDB v10+ no longer functions as a MySQL drop-in replacement, and it’s not supported for Mattermost due to the requirement of MySQL 5.7.12. Prior versions of MariaDB were not officially supported but may have functioned in older Mattermost releases. If you are running MariaDB now, migrating from MariaDB to the MySQL equivalent is recommended.

**Comment by mgdelacroix** [comment]
We could tone down the error to say something less "radical" like `this version of Boards doesn't support MariaDB` if preferred, and even add a link to the code debt item, so users will know that we plan to make an effort to remove the non-compatible code.

The effect will still be that Boards is not going to work as of now, but they'll have a pointer to follow besides the error message.

**Comment by wiggin77** [comment]
> and even add a link to the code debt item,

@mgdelacroix I guess adding the link sbishel posted (https://docs.mattermost.com/install/software-hardware-requirements.html#database-software) would give the user some info.

**Review by wiggin77 — APPROVED** [review]

**Comment by mgdelacroix** [comment]
Error message updated on [59d6739](https://github.com/mattermost/focalboard/pull/3725/commits/59d6739a269b76c3cac0b3d635e67e064ead960d)

**Review by sbishel — APPROVED** [review]

**Pull request merged**
