### PR TITLE
Added URL as a property on the frontend

### PR DESCRIPTION
**Pull request by BharatKalluri**
Added URL as a proprty option on the frontend

#### Summary

Takes https://github.com/mattermost/focalboard/pull/84 as a reference 😅 and adds a URL prop on the frontend. Seems like its already a part of `propertyValue`

#### Ticket Link

https://github.com/mattermost/focalboard/issues/37

I had one small question, eventually will focalboard have validations on the text in the propertyValue?

### CODE REVIEW

**Comment by chenilim** [comment]
Thanks for the PR @BharatKalluri! Let's hold off on this one for now.

Currently the 'text', 'number' and 'email' properties all map to an `Editable` text field. They should instead map to distinct controls with validation, etc. For instance, we should not be able to enter letters into a number field. Emails and URLs should be validated.

**Comment by jespino** [comment]
@BharatKalluri I added a property validator mechanism in master, do you mind to merge master in your branch and add the `url` validator there? With that, I think this PR is ready to go.

**Comment by BharatKalluri** [comment]
Sure, I'll be adding the URL regex from https://www.urlregex.com/

The regex for a URL is given to be 
`/((([A-Za-z]{3,9}:(?:\/\/)?)(?:[\-;:&=\+\$,\w]+@)?[A-Za-z0-9\.\-]+|(?:www\.|[\-;:&=\+\$,\w]+@)[A-Za-z0-9\.\-]+)((?:\/[\+~%\/\.\w\-_]*)?\??(?:[\-\+=&;%@\.\w_]*)#?(?:[\.\!\/\\\w]*))?)/`

**Review by jespino — APPROVED** [review]
Now looks good to me. Thanks! :tada:

**Pull request merged**
