### PR TITLE
Update telemetryClient.ts

### PR DESCRIPTION
**Pull request by wuwinson**

### CODE REVIEW

**Comment by jespino** [comment]
It is not that simple, if you explain me the intention here, I can update the whole code to accept properly this change.

**Comment by wuwinson** [comment]
@jespino I was trying to update to telemetry ID so it's a bit clearer on what is actually being tracked through that ID. I assumed only the section between apostrophe was referenced in the code and not the part I updated. Not worth the trouble if this requires updating the whole code.

**Comment by jespino** [comment]
@wuwinson actually it is all the way around, there is nothing wrong in updating any side, but I going to explain. The left side, is the code part, everywhere you use that in the code, you should be using the left side. The right side is the event name that is send for telemetry, if we change the right side, the code doesn't gets affected, but the telemetry is going to start counting it as a different event, and is going to "break" the stats (break here means, start counting from zero the new event type, and leave untouch the old event type).

Renaming this in the code can be really useful from our side, and I'm ok doing it. And I guess we want to preserve the event name to not mess the stats, right?

**Comment by wuwinson** [comment]
Yep, that makes sense, thanks for clarifying @jespino! We do indeed want to preserve the event name to not mess up the stats. If it's not too much trouble renaming it in the code, then it would be great to have it updated so it's clearer on what the ID is tracking. Thanks!

**Comment by chenilim** [comment]
Hi @wuwinson, late to this, but in general we should avoid changing existing event IDs, because tracking them across the change will be very difficult. In this case, as long as we know that "CreateBoard" means "an empty board was created", that's ok. I advise not making this change.

In the future, let's say we need to add a "CreateNonEmptyBoard" (hypothetically), we can add that.

**Comment by wuwinson** [comment]
Sounds good @chenilim, closing this out.

**Pull request closed without merging**
