### PR TITLE
Fix Cards not Dragging to different Columns (GH-626)

### PR DESCRIPTION
**Pull request by hahmadia**
#### Summary

If you create a new card and then try to drag to a new group, it won't work because boardTree is out of sync. 
Sometimes boardTree is not in sync and it causes cards not being able to be dragged to different columns hence we need to useRef to fix this.

#### Ticket Link

Fixes GH-626

### CODE REVIEW

**Comment by kamre** [comment]
@hahmadia what is the reason for `boardTree` to be out of sync? Just switching to `useRef` looks like a workaround and not a fix for the real problem.

It seems that real problem is the same that I have described [here](https://github.com/mattermost/focalboard/issues/708#issuecomment-880497103). So we might just need to pass dependencies for `useDrop` inside `kanbanColumnHeader.tsx`

**Review by harshilsharma63 — APPROVED** [review]
LGTM!

**Comment by kamre** [comment]
@harshilsharma63 @hahmadia The reason for `boardTree` to be out of sync is the following:
* everytime `const Kanban = (props: Props) => {` is called to render the component new closure is created and assigned to `const onDropToColumn = async (...) => {`
* this new closure for `onDropToColumn` is passed as callback prop to `KanbanColumnHeader`, `KanbanColumn` and `KanbanHiddenColumnItem`
* inside all of these components `useDrop` hook is used and `onDropToColumn` callback is used inside the object created for this hook
* `useDrop` has [additional argument for dependencies](https://react-dnd.github.io/react-dnd/docs/api/use-drop) with "_default value is an empty array for function spec_"
* so for the first render of `Kanban` the closure for `onDropToColumn` is created, passed to `useDrop` and is never updated inside it though new closures are created again and again that capture acutal values for `boardTree` and other variables in the scope

When `useRef` is used for the `boardTree` there is still the same first closure for `onDropToColumn` inside the `useDrop` hook. And this first closure actually **captures other variables** that **will not be in sync** and we will encounter the same problem as we have seen for `boardTree`.

Proper solution can be updating of the closure used for `useDrop` hook like this so that it doesn't cache the closure with outdated captured values:
```ts
export default function KanbanColumnHeader(props: Props): JSX.Element {
    ...
    const [{isOver}, drop] = useDrop(() => ({
        accept: 'column',
        collect: (monitor) => ({
            isOver: monitor.isOver(),
        }),
        drop: (item: IPropertyOption) => {
            props.onDropToColumn(item, undefined, group.option)
        },
    }), [props.onDropToColumn])  // <== add dependency
    ...
}

const KanbanColumn = React.memo((props: Props) => {
    const [{isOver}, drop] = useDrop(() => ({
        accept: 'card',
        collect: (monitor) => ({
            isOver: monitor.isOver(),
        }),
        drop: (item: Card, monitor) => {
            if (monitor.isOver({shallow: true})) {
                props.onDrop(item)
            }
        },
    }), [props.onDrop])   // <== add dependency
    ...
}

export default function KanbanHiddenColumnItem(props: Props): JSX.Element {
    const {boardTree, intl, group} = props
    const {activeView} = boardTree
    const [{isOver}, drop] = useDrop(() => ({
        accept: 'card',
        collect: (monitor) => ({
            isOver: monitor.isOver(),
        }),
        drop: (item: Card) => {
            props.onDrop(item)
        },
    }), [props.onDrop])  // <== add dependency
    ...
}
```

**Comment by harshilsharma63** [comment]
@kamre you're right. The ref solves it for one variable, but what you're proposing will avoid issues with anything used in `onDrop` and `onDropToColumn`. @hahmadia can we make this change, please?

**Pull request merged**
