### PR TITLE
Add Docker volume persistence

### PR DESCRIPTION
**Pull request by MrLemur**
#### Summary
This sets a default volume of `/data` for the Docker container.

This allows for persistence when using the default SQLite database and uploaded files, plus the option of mounting the volume to the host for backing up.

### CODE REVIEW

**Comment by chenilim** [comment]
Thanks for the PR @MrLemur! Sorry for the delay. @flexo3001 or @jwilander, do you have any input on this?

**Review by jwilander — APPROVED** [review]
LGTM

**Review by flexo3001 — COMMENTED** [review]
LGTM

**Comment by jasonblais** [comment]
@jespino is this one good to merge?

**Comment by chenilim** [comment]
Going through stale items. @jespino, if this looks good to you, can you merge? I don't have much Docker experience myself, but the change sounds pretty straight forward.

**Review by jespino — APPROVED** [review]
LGTM

**Comment by jespino** [comment]
I going to merge this after the #168 PR

**Comment by seungjaeryanlee** [comment]
> I going to merge this after the #168 PR

Looks like PR #168 is merged. May I ask if there is a reason this is not merged yet?

**Comment by jespino** [comment]
@seungjaeryanlee sorry, my bad, I missed this.

**Pull request merged**
