### PR TITLE
GH-364 Automatically open new card for editing

### PR DESCRIPTION
**Pull request by rohit1101**
@chenilim 

> For this particular issue, I think we can fix @Johennes's original issue directly, i.e. when clicking on the + New on the board columns, open the card by default. This is consistent with clicking on the New button.

> And also do the same when clicking on +New in Gallery view

I have made the changes in Kanban.tsx and gallery.tsx for the required feature idea.

And all my tests passed.

I ran these commands for testing: (in /src/webapp)

1. Webapp eslint: npm run check
2. Webapp unit tests: npm run test
3. Webapp UI tests: npm run cypress:ci

### CODE REVIEW

**Review by jespino — CHANGES_REQUESTED** [review]
Again you are regenerating the `package-lock.json` that is not needed for this change, please remove that from the comment, other than that looks good to me. Thanks @rohit1101! :tada:

**Comment by rohit1101** [comment]
@jespino Think I made the necessary changes and reverted package-lock.json.
Hope my PR gets merged!

**Review by jespino — APPROVED** [review]
Now looks good to me. Thanks @rohit1101! :tada:

**Pull request merged**
