### PR TITLE
Generate templates archive at build time

### PR DESCRIPTION
**Pull request by wiggin77**
#### Summary
This PR includes support for generating a default templates archive and embedding that at build time.  The archive is generated based on a checked-in file tree containing an exported set of templates.  

This PR also ensures older archive formats can be imported by filling in the missing fields adding for permissions.

#### Ticket Link
fixes https://github.com/mattermost/focalboard/issues/2558

### CODE REVIEW

**Review by sbishel — APPROVED** [review]
LGTM

**Comment by jespino** [comment]
If this is generating and embedding the file in the fly, should we remove the archived from the repo?

I mean the file: `server/assets/templates.boardarchive`

**Review by jespino — APPROVED** [review]
LGTM

**Pull request merged**
