### PR TITLE
Fix GH-1727: Board calculations: Dates are cut off

### PR DESCRIPTION
**Pull request by hahmadia**
#### Summary

Fixes GH-1727

#### Ticket Link

Fixes GH-1727

image

image

### CODE REVIEW

**Comment by hahmadia** [comment]
@asaadmahmood

Is this fix okay for #1727 ?

**Comment by asaadmahmood** [comment]
@hahmadia I think a better fix for this would be to allow for 5 characters and format the dates like:
`Nov 31`
`May 05` etc

**Review by asaadmahmood — CHANGES_REQUESTED** [review]
See comment.

**Comment by hahmadia** [comment]
Discussed in meeting we will take this as is. I will create new tickets for your changes Asaad.

**Comment by hahmadia** [comment]
Hi Asaad,

I've created a follow up ticket for the changes you have requested.
https://github.com/mattermost/focalboard/issues/1788

**Review by asaadmahmood — APPROVED** [review]

**Review by sbishel — APPROVED** [review]

**Pull request merged**
