### PR TITLE
Fixing a weird import bug on react-day-picker

### LINKED ISSUE #918: Bug: Error when selecting a date property in card view
**Summary:**
When selecting a date property in card view you receive a page that simply states 

"Something went wrong."

Javascript error "Cannot read property 'localeData' of undefined"

**Steps to reproduce the behavior:**
1. Go to any card.
2. Create a new Date Property
3. Click on "Empty" to load the day picker.

**Expected behavior:**
Day Picker is loaded successfully.

**Screenshots:**
Screen Shot 2021-08-10 at 12 28 39 PM

**Platform:**
 - Browser and version: Chrome 92
 - OS and version: macOS 11.4

**Additional context:**

### PR DESCRIPTION
**Pull request by jespino**
Fixes  #918

### CODE REVIEW

**Review by wiggin77 — APPROVED** [review]
I trust this alias resolves the build error.  What I don't understand is how the build error got past CI and deployed??

**Review by sbishel — APPROVED** [review]
Tested locally, builds without warning, works as plugin

**Comment by ogi-m** [comment]
Tested and passed on RC4 - date picker opens as expected

**Pull request merged**
