### PR TITLE
Disable the view dropdown selector on public "read-only" 

### PR DESCRIPTION
**Pull request by redhoyasa**
#### Summary

Disable the view dropdown selector on public "read-only" so the complete list of views won't be shown.

**Before**
Screenshot 2022-11-07 at 10 10 03 PM

**After**
Screenshot 2022-12-09 at 4 47 46 PM

#### Ticket Link

Fix https://github.com/mattermost/focalboard/issues/2932

### CODE REVIEW

**Comment by Rajat-Dabade** [comment]
Changes look good to me @redhoyasa, Nice work 🚀 .

Though I think the dropdown button to change the view is still clickable, which should not be. Can you please make it disabled (`cursor: not-allowed` maybe)?

Also, I can see we have some test-case failures, mostly snapshots because of your changes.  You can run 
`npm run test -- -u` in the `webapp` directory to fix it. 

Thanks

**Comment by wuwinson** [comment]
Awesome work @redhoyasa! Would it be possible to hide the dropdown button altogether, but leave the view name visible? It occurred to me that users might think they are encountering a bug if they see a dropdown button, but won't be able to click on it. If not, then disabling the button works too. Thanks!

**Comment by redhoyasa** [comment]
Hi @wuwinson, sorry for waiting for a long time. I already removed the dropdown icon. Could you please review it again?

Thanks!

**Comment by wuwinson** [comment]
Awesome work @redhoyasa! Looks great to me! @Rajat-Dabade Can you review and approve if everything looks good on your end? Thanks all!

Screen Shot 2022-12-09 at 5 51 03 PM

**Comment by wuwinson** [comment]
Thanks again @redhoyasa @Rajat-Dabade!

**Pull request merged**
