### PR TITLE
Made calculation options hidden when empty:

### LINKED ISSUE #960: Only show table calculate controls on hover
**Summary:**
Currently, the table calculate row is always visible:
Table calculate row

This adds visual noise, and is mostly unnecessary as users will typically set this once or a few times, and only for a few columns.

Proposal:
* Hide the un-set (default state) calculate controls until the user hovers over them
* But always show the controls that are set

### PR DESCRIPTION
**Pull request by harshilsharma63**
#### Summary
Displaying table calculation options only when not empty and on hover.

#### Ticket Link
Fixes #960

### CODE REVIEW

**Comment by harshilsharma63** [comment]
@asaadmahmood can you run this and verify the UX?

**Comment by asaadmahmood** [comment]
@harshilsharma63 For this one, we want to show all the calculate dropdowns if a person is hovering over the row.

**Review by asaadmahmood — CHANGES_REQUESTED** [review]
See comment. Also we can make the Calculate option by default a bit greyed (opacity .6) but if it has a value, we bump up the opacity to default (1).

**Comment by harshilsharma63** [comment]
@asaadmahmood can you take a look at this again? I've made the required changes.

**Review by asaadmahmood — CHANGES_REQUESTED** [review]
The hover doesn't work on the plugin.

**Pull request merged**
