### PR TITLE
Marketing/website redesign

### PR DESCRIPTION
**Pull request by emdecr**
#### Summary
This branch encompasses the redesign of the focalboard.com website.

#### Ticket Link
On Marketing Asana Board:
https://app.asana.com/0/1201867728201087/1201774448360374/f

@chenilim A few questions:

- I vaguely remember you mentioning you'd prefer images hosted outside of the repo. What's the protocol around that again? 
- We don't have staging sites for preview purposes, right? Asking because I'd like to send JuliAnn a link to review.
- Also let me know if there's a preferred way to go about PRs like this. 

Thanks!

### CODE REVIEW

**Comment by chenilim** [comment]
Thanks @emdecr! New design looks great!

For hosting large images, the procedure is:
1. Post a discussion and attach an image ([example for the current hero PNG](https://github.com/mattermost/focalboard/discussions/578))
2. Copy the link and use it in the code ([example](https://github.com/mattermost/focalboard/blob/main/website/site/layouts/partials/hero.html#L28)).

This avoids storing the large binaries in the source control. It's a bit of a gray area, but I would avoid checking in images larger than 100KB. e.g. the logos and icons are generally fine, but consider offloading the larger images.

As for testing, you can run the site locally with `make run` from the website folder, then open `http://localhost:1313`. Since Hugo generates a static site, the dist folder could be hosted anywhere (or zipped) if you want to share it with someone else.

**Review by chenilim — CHANGES_REQUESTED** [review]
New site looks great! Recommend offloading the larger images:
`website/site/static/img/focalboard-careers.png`, and
`website/site/static/img/focalboard-open-source.png`

**Comment by emdecr** [comment]
@chenilim Thanks for the context and feedback. I've off-loaded the images to this discussion:
https://github.com/mattermost/focalboard/discussions/2883

Once JuliAnn gives the go-ahead, am I okay to remove the Do Not Merge and Work in Progress labels to let it go through the normal PR process?

**Review by chenilim — APPROVED** [review]
Looks good @emdecr! When you have final sign off, go ahead and remove the do-not-merge tag, and ping me, and I can merge it.

In the meantime, or at the same time, you can go ahead and build and push to production using the steps we went over. You don't need to wait for the merge. LMK if you need help or run into any issues. Thanks!

**Comment by emdecr** [comment]
@chenilim We should be all good to merge. I also added a note about versioning in Commit https://github.com/mattermost/focalboard/pull/2881/commits/803b372cdb84e64cea12e11cfc16d408c87ea8fe (in the README).

Also needed to add some version params to the main logos, so we should do another invalidation whenever you have time.
Thanks for all your help and guidance!

**Review by chenilim — APPROVED** [review]
Awesome! Thanks again for the great work on this! I've run another invalidation. LMK if you need to make further updates.

**Pull request merged**
