### PR TITLE
Fix position of flash message popup see #3898

### LINKED ISSUE #3898: Popup is not aligned
## Summary
Found on `https://boards-bugbash73.test.mattermost.cloud/`server >Private Board
In this section we click on three dots and select `Copy Link` Option Copied popup is not alligned
feature1

### PR DESCRIPTION
**Pull request by vivekkj123**
#### Summary

This pull request will fix #3898 which is caused by a CSS mistake. As we're already using `left:50%` and `position: fixed`,  `margin: 0 auto;` is unnecessary and removing it solved the problem.

Screenshot (After)

ss

#### Ticket Link
  Fixes https://github.com/mattermost/focalboard/issues/3898

### CODE REVIEW

**Review by harshilsharma63 — APPROVED** [review]
Awesome work! LGTM 👍

**Comment by wuwinson** [comment]
@vivekkj123 @harshilsharma63 Does this impact the pop-up positioning when the card dialog is not open?

https://user-images.githubusercontent.com/93531870/194136383-b3c67c7b-0b93-4512-aaff-fd946f20ca34.mov

**Comment by wuwinson** [comment]
> Screenshot_20221006_184208
> 
> They will be also aligned properly.

Great, thanks!

**Pull request merged**
