### PR TITLE
Fix to respect System Console settings

### PR DESCRIPTION
**Pull request by sbishel**
#### Summary
Fix to respect full name and email configuration settings. We currently don't return email in the user json, but implemented it as well when using plugin.

Did not implement on the Personal server side as we don't set/retrieve `LastName` and `FirstName` and as stated above, we don't return the `Email` in the user json.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-48009

### CODE REVIEW

**Review by wiggin77 — APPROVED** [review]
LGTM :+1:   My only nit is that no tests have the true, true values.

**Comment by sbishel** [comment]
> LGTM 👍 My only nit is that no tests have the true, true values.

Agreed, but because it wasn't implemented in Personal Server. Setting the tests to true, true values would have no effect. And we, unfortunately, have any tests for `mattermostauthlayer` - (which I just created a card for)

**Pull request merged**
