### PR TITLE
Implement Person filter and groupBy

### PR DESCRIPTION
**Pull request by sbishel**
#### Summary
Implement Person filter and grouping.

#### Ticket Link

https://community.mattermost.com/boards/team/qghzt68dq7bopgqamcnziq69ao/b4ctmm917q3rzdfi451qtuxjzcw/vuswsftt1rb873datosmmbtwkpa/cjj9fh6tonpgtdjiifp5768mb3e

### CODE REVIEW

**Comment by harshilsharma63** [comment]
I'm testing and reviewing this now. Found one minor bug for now -

In table view, if you group by a person property, it shows `undefined` for the group title with cards that don't have an assignee.
Screenshot 2023-01-04 at 8 16 30 PM


Other than this I experienced an error on sorting and grouping by the same property at the same time, but now its working fine. I'll see if I can reproduce it still.

**Comment by sbishel** [comment]
@harshilsharma63 - fixed minor issue, I tried with same sort and group with person, but couldn't duplicate. Let me know if you have steps.

**Review by harshilsharma63 — APPROVED** [review]

**Comment by ogi-m** [comment]
@sbishel I'm seeing one issue with the _Last updated by_ property. Looks like the card creator gets included:
Card 2 and Card 3 were last updated by `ogi-user2` but they're showing up in the filter for cards last updated by `ogi-m` (`ogi-m` is the card creator)
Screenshot 2023-01-10 at 13 00 33


And a question - are these two being split into phase 2?

Screenshot 2023-01-10 at 12 46 21

**Comment by sbishel** [comment]
@ogi-m - I can't duplicate the filtering issue you're seeing. Perhaps tomorrow we can jump on a call. 
Option to select "Me". - I just implemented, missed it. 
Search Bar - It does exist, I updated the text to say "search", to try and make it more obvious. This is essentially the same control as used in the properties, so we may have to have Asaad play with css to get it different. I think we can enhance it later if necessary.

**Comment by sbishel** [comment]
@ogi-m - Should be ready to retest.

**Review by Rajat-Dabade — APPROVED** [review]
Looks good to me, Nice work 🎉 @sbishel 

Found one minor CSS issue regarding collapsing when grouping by person, the top card doesn't collapse, not sure whether it is on purpose.

https://user-images.githubusercontent.com/26198062/212818126-bcf65295-1763-4a41-a12f-622aa15caf54.mov

**Comment by sbishel** [comment]
@Rajat-Dabade - Not on purpose...nice catch. Opened issue https://github.com/mattermost/focalboard/issues/4479 to track.

**Pull request merged**
