### PR TITLE
Typing adjustment - 1354

### PR DESCRIPTION
**Pull request by tiago154**
#### Summary

Hello.

Adjusted the warnings in the file
`webapp/src/octoClient.ts`

where the typing from `any` to `unknown` was changed.

#### Ticket Link

#1354

### CODE REVIEW

**Comment by harshilsharma63** [comment]
@tiago154 thanks a lot for the PR and the fixes. There are 2 errors though. There are some type assertions missing when using unknown. Please compile the project and try running it to see the errors.

**Review by harshilsharma63 — CHANGES_REQUESTED** [review]
Need to fix type assertions for unknown.

**Comment by tiago154** [comment]
Hello @harshilsharma63 .

Thanks for letting me know. I made some adjustments to the typing and I believe it is now correct.
I compiled the project and now it returns no errors.

**Review by harshilsharma63 — APPROVED** [review]
Awesome! LGTM!

**Pull request merged**
