### PR TITLE
Porting the card limits frontend to main branch

### PR DESCRIPTION
**Pull request by jespino**

### CODE REVIEW

**Comment by wiggin77** [comment]
@jespino FYI there are some webapp compile errors remaining.

**Comment by jespino** [comment]
@wiggin77 this should be ready now

**Comment by wiggin77** [comment]
@jespino , it looks like there is an empty file added:  webapp/src/components/cardLimitNotification.scss

**Review by wiggin77 — APPROVED** [review]
LGTM  :+1:    Just one empty file likely should be removed.

**Pull request merged**
