### PR TITLE
Allow empty dates returned from date property

### LINKED ISSUE #4181: Bug: Dates with empty values don't update when moving cards on calendar view
## Steps to reproduce the behavior

1. Create a card with an empty date property
2. Go to calendar view
3. Display by the date property
4. Move the card from step 1 to another date
5. See error - date on the property is not updated

## Expected behavior

Cards should not appear on the calendar if they do not have a date on the date property. Date property is updated based on the date selected. Works find on cards with existing dates on the date property.

## Screenshots (optional)

https://user-images.githubusercontent.com/93531870/200697467-69207976-a0b8-4da5-8431-3c35a89cf400.mov

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v7.5 Bug Bash
 - Browser and OS: Chrome on Mac

### PR DESCRIPTION
**Pull request by sbishel**
#### Summary
Currently if a date property does not contain a value, the "createAt" property is returned. Dates are not allowed to return undefined. This results in calendar items being displayed by their "CreateAt" property if the Calendar's "Date" Property is not defined.

This PR updates properties to allow dates to be returned as undefined.

#### Ticket Link
  Fixes #4181

### CODE REVIEW

**Review by jespino — APPROVED** [review]
LGTM

**Review by Rajat-Dabade — APPROVED** [review]
LGTM as well 👍

**Pull request merged**
