### PR TITLE
focalboard.com edits

### PR DESCRIPTION
**Pull request by emdecr**
#### Summary
Post-launch there have been a few copy tweaks. I will replace the actual files in the S3 Bucket, but will leave this PR open for a week or so just in case we catch any more. Then we can do one merge with all the edits.

cc: @chenilim

### CODE REVIEW

**Comment by emdecr** [comment]
@chenilim Going to submit this PR as it seems no changes have popped up since we launch.
This PR covers a casing issue with GitHub in the nav.

I've updated the s3 bucket – can you create an invalidation on Cloudfront (still going through approval process so I can get access) when you have the time? No rush - thanks!

**Comment by chenilim** [comment]
@emdecr - sorry was on PTO last week. Just created an invalidation. LMK if anything doesn't look right. Thanks.

**Comment by emdecr** [comment]
@chenilim Totally all good! Paul gave me the heads up. Thanks for the invalidation. Looks good!

**Review by chenilim — APPROVED** [review]

**Comment by emdecr** [comment]
@chenilim Thanks for circling back on this one!

**Pull request merged**
