### PR TITLE
Fix #2333. Handle export in Mac App

### LINKED ISSUE #2333: Bug: Export archive doesn't work on Mac Personal Desktop
## Steps to reproduce the behavior

1. Open Personal Desktop 0.14.0
2. Open a Board
3. Select "Export board archive" from the board menu
4. Or select "Export archive" from the bottom left settings menu
5. Nothing happens

## Expected behavior

The archive can be downloaded

## Edition and Platform

 - Edition: Personal Desktop Mac
 - Version: v0.14.0
 - Browser and OS: macOS 11.6.2

### PR DESCRIPTION
**Pull request by chenilim**
#### Summary
Implement the new (for Big Sur) WKDownloadDelegate to handle downloads. Note that this bumps the macOS requirement to 11.3 (up from 10.14).

#### Ticket Link
#2333

### CODE REVIEW

**Review by sbishel — APPROVED** [review]
I'm not real sure what I'm looking at, but LGTM.  :)

**Comment by sbishel** [comment]
@chenilim - there is a build failure.

**Comment by chenilim** [comment]
Thanks, the build failure is because the workflows are running an old Xcode version (12.4). I'll submit a PR to update the workflow to use the latest (macOS 11 and Xcode 13.2.1).

**Comment by wiggin77** [comment]
@chenilim are you sure you want to delete existing file on collision versus append a number to make unique?

**Comment by chenilim** [comment]
@wiggin77 in the file picker, on clicking Save, a warning message is shown prompting the user to replace the file:

Screen Shot 2022-02-14 at 4 06 40 PM

The delete code executes after the user chooses to replace, and I believe this matches the user intent.

**Review by wiggin77 — APPROVED** [review]
I'm not an expert in Swift but it looks good.  👍

**Comment by chenilim** [comment]
PR to update workflow macOS and Xcode version is https://github.com/mattermost/focalboard/pull/2338. I'll merge this in after that is merged.

**Pull request merged**
