### PR TITLE
Fixes for cypress tests

### PR DESCRIPTION
**Pull request by sbishel**
#### Summary
Took @kamre patch he provided here - https://github.com/mattermost/focalboard/pull/2676#issuecomment-1082226961

And applied that patch to fix cypress tests...

#### Ticket Link
  Fixes https://github.com/mattermost/focalboard/issues/2670

### CODE REVIEW

**Comment by chenilim** [comment]
Looks like we need to merge the fix for https://github.com/mattermost/focalboard/pull/2676 before we can validate this passes the Cypress tests in GitHub.

**Review by chenilim — APPROVED** [review]
Looks good! Tests pass!

**Comment by sbishel** [comment]
Thanks @kamre for the quick fix.

**Pull request merged**
