### PR TITLE
Added ability for calculation menu to open wherever there is available space

### LINKED ISSUE #930: Bug: Table column calculations > Calculate dropdown height is limited by the table height
**Summary:**
_Calculate_ dropdown height is limited by the table height, so where there are only a few items in the table it appears cut off and doesn't display all the options 

**Steps to reproduce the behavior:**
1. Open table view and make sure there's only a few rows
2. Add a number type property
3. Click on calculate below the numbers column

**Expected behavior:**
Dropdown opens fully and reveals all 10 options.

**Screenshots:**
Screenshot (21) Screenshot (19)

### PR DESCRIPTION
**Pull request by harshilsharma63**
#### Summary
Added ability for calculation menu to open wherever there is available space

#### Ticket Link
Fixes #930 

It opens the menu at the bottom by default and opens above if there is no space below

Screenshot 2021-08-12 at 4 09 07 PM

This changes the behaviour from the default top menu to the default bottom menu. Unfortunately, there is no way in react select to set default menu placement to top and open in the bottom only if there is no space.

### CODE REVIEW

**Review by jespino — APPROVED** [review]
LGTM

**Comment by harshilsharma63** [comment]
@ogi-m can you review this on the latest `main`? I'll cherrypick to 0.9 once you approve.

**Comment by ogi-m** [comment]
@harshilsharma63 LGTM, the menus now open downwards if there's too few rows in the table and show all options 👍🏻

**Comment by harshilsharma63** [comment]
Thanks @ogi-m .

**Pull request merged**
