### PR TITLE
Remove temporary share button / update share button

### PR DESCRIPTION
**Pull request by sbishel**
#### Summary
Remove temporary share button. The required share button is also there already.

This PR also only displays the share button but only displays the users if the user is an Admin for the board. It also uses the config setting for EnableSharedBoards with the share dialog itself.

This PR also fixes some merge issues that have occurred around this feature.

#### Ticket Link

  Fixes https://github.com/mattermost/focalboard/issues/2376

Screen Shot 2022-02-22 at 6 06 55 PM

### CODE REVIEW

**Review by wiggin77 — APPROVED** [review]
LGTM :+1:

**Comment by sbishel** [comment]
I actually need to make some additional updates in order to show the Share button if user is admin...currently it is based on on "allowSharing" config setting (from v0.15)

**Review by harshilsharma63 — APPROVED** [review]
LGTM 👍

**Review by asaadmahmood — APPROVED** [review]

**Comment by sbishel** [comment]
Closing this in favor of - 
https://github.com/mattermost/focalboard/pull/2536

**Pull request closed without merging**
