### PR TITLE
Minor improvements for VSCode

### PR DESCRIPTION
**Pull request by kamre**
#### Summary
Minor improvements for VSCode:
* chrome launch configuration for webapp added so that it is possible to debug webapp in VSCode
* include `*.tsx` files in `tsconfig.json` so that jest tests inside `*.tsx` files don't show errors about not found jest functions
* tabs replaced with 4 spaces in `launch.json`

### CODE REVIEW

**Comment by jespino** [comment]
@harshilsharma63 I don't use VSCode, I don't know if you do, if not, you can pass it to another developer that use it.

**Comment by harshilsharma63** [comment]
@jespino I use Intellij Idea. I'm sure @chenilim uses VS Code. Added him as the reviewer.

**Comment by jespino** [comment]
@harshilsharma63 Great, thanks! :)

**Comment by harshilsharma63** [comment]
@kamre can you explain a bit how can I try this out?

**Comment by kamre** [comment]
@harshilsharma63 this can be done for debugging in VSCode:
* build server and webapp
* run the server from console
* activate _Run and Debug_ panel in VSCode
* select _Launch Chrome_ configuration and start it
* Chrome should be started and VSCode will attach to it for debugging
* its possible to set breakpoints in webapp code in VSCode, do something in the opened Chrome and hit breakpoints

**Comment by harshilsharma63** [comment]
Screenshot 2021-07-07 at 12 16 32 PM

I'm able to launch chrome but the breakpoints I'm setting are coming out as unbound breakpoints. Anything else that I need to do?

**Comment by kamre** [comment]
@harshilsharma63 couple questions:
* do you use _development build_ for `webapp` that has source maps?
* can you see that source maps are picked by the opened Chrome in its dev tools? One time I had to clean cache in Chrome for it to pick new development build.

**Comment by harshilsharma63** [comment]
@kamre awesome! I got it to work. Works beautifully. LGTM.

**Review by harshilsharma63 — APPROVED** [review]

**Pull request merged**
