### PR TITLE
Fix kanban cards overlapping with header

### PR DESCRIPTION
**Pull request by xMicky24GIT**
#### Summary
**Before**: 
before

**After**:
after

### CODE REVIEW

**Comment by asaadmahmood** [comment]
@xMicky24GIT is this issue reproducing on main? I can't seem to reproduce it.

**Comment by xMicky24GIT** [comment]
@asaadmahmood Yes I downloaded and builder everything yesterday. This happens when you scroll horizontally if there are columns outside of the width of the screen

**Comment by asaadmahmood** [comment]
@xMicky24GIT I tried that, can't reproduce it, I was able to reproduce this issue earlier, but not right now.
Here's a read only board, try and see if you can reproduce the issue on it:
https://community.mattermost.com/boards/workspace/qgsck6cts3fwpqwyjiupjm5cde/shared/47aa9bb4-6967-4a96-83c7-11bd6b20f1eb/7e38eab4-890a-4fc3-8f48-a1f9bd1ab822?r=762db9c6-305c-4d13-8ce6-9f11e5232c24

**Comment by xMicky24GIT** [comment]
@asaadmahmood 
For me it is happening here too, the main header isn't long enough
image

**Comment by asaadmahmood** [comment]
Strange, for me the header expands the whole width. Which browser are you on?
Screenshot 2021-09-17 at 7 35 39 PM
.

**Comment by xMicky24GIT** [comment]
I'm on Firefox 92

**Comment by kamre** [comment]
@xMicky24GIT @asaadmahmood I can't reproduce the issue on c64e6ed0066:
KanbanHeaderScroll

**Comment by asaadmahmood** [comment]
Same, can't reproduce it, tried firefox 91.0.2 (64-bit) on Mac as well.

**Comment by kamre** [comment]
Tried Firefox 92 on Windows 10 and it really looks like this:
image

**Comment by xMicky24GIT** [comment]
A friend on firefox on windows has the same problem that's why I tried to search for a fix. I downloaded Chromium now and it doesn't have this problem

**Comment by asaadmahmood** [comment]
Okay, so it's an issue with firefox on windows.

**Review by asaadmahmood — APPROVED** [review]

**Comment by xMicky24GIT** [comment]
> Okay, so it's an issue with firefox on windows.

On linux too

**Comment by kamre** [comment]
Reproducible on `v0.9.0` by the way.

**Comment by kamre** [comment]
Can also be fixed in Firefox via `width: -moz-fit-content;`

**Comment by chenilim** [comment]
Trying to clean up stale PRs. @asaadmahmood, @harshilsharma63: Is this good to merge or are there changes still needed. Has anyone verified that this fixes the issue on FireFox on Windows / Linux? cc @ogi-m.

**Review by harshilsharma63 — APPROVED** [review]
Even though I can't reproduce the original issue, it looks fine with these changes applied. 

I'm fine merging this if it solves the issue for some.

**Pull request merged**
