### PR TITLE
Replace go migrate with morph permissions

### PR DESCRIPTION
**Pull request by isacikgoz**
#### Summary
As suggested, we can merge this into the feature branch first.

Alter ego of #2363

### CODE REVIEW

**Comment by agnivade** [comment]
@sbishel @wiggin77 @jespino  - Can we have someone from the focalboard team look into this? This is important to move forward with the multi-product architecture. As suggested by Doug in the other PR, we have shifted the PR into the migrations branch. We are looking for a review from the team to take this forward. Thanks!

**Comment by jespino** [comment]
I'll review it today.

**Review by jespino — APPROVED** [review]
LGTM

**Comment by jespino** [comment]
@agnivade if this gets merge into the permissions-branch this is not going to be available until the April release, just to let you know.

**Comment by agnivade** [comment]
Wow that was too fast! I think there were some CI failures to fix :stuck_out_tongue_closed_eyes: 

Anyways, yes it's fine to be available in April release. There is no rush, we just wanted to get this merged in some form or other.

**Comment by jespino** [comment]
Yes, looks good to me, the CI was passing in most of the tests, so means that this is doing the job properly.

Also I want to migrate that from binddata to embed, but that is going to be a bit later, maybe the next week.

**Pull request merged**
