### PR TITLE
Custom template's default card template works

### PR DESCRIPTION
**Pull request by Rajat-Dabade**
#### Summary
This PR will make the Custom template's default card template to be used when the new button is clicked for the first time

#### Ticket Link
Fixes https://github.com/mattermost/focalboard/issues/3036

### CODE REVIEW

**Comment by Rajat-Dabade** [comment]
@mgdelacroix I have set all the defaultTemplateID to an empty string so that it will point to the empty card whenever someone uses these predefined templates as suggested by @wuwinson.

**Review by sbishel — APPROVED** [review]
Go ahead and assign yourself a ticket to create unit tests for `blockid.go`. It can be done in the next week. 

Also, I think you need to run 
`make templates-archive` 
when you update the templates. And update version [here](https://github.com/mattermost/focalboard/blob/main/server/assets/templates-boardarchive/version.json)

@wiggin77 can confirm. 

Otherwise LGTM.

**Review by mgdelacroix — APPROVED** [review]
Code LGTM! :+1: I was just about to suggest creating an unit test before I saw @sbishel's comment

**Pull request merged**
