### PR TITLE
[GH-1732] Add person filter

### LINKED ISSUE #1732: Bug: filters are not including "person" type fields
## Steps to reproduce the behavior

1. Create a property of type "person" on a card
2. Try to add a filter so that a board only shows cards with that property not empty

## Expected behavior

The app should allow me to create such filter, but I won't see the property amongst those I can use for a filter

## Edition and Platform

 - Edition: Mattermost plugin
 - Version: v0.10.0 RC
 - Browser and OS: Firefox 93 on Linux

### PR DESCRIPTION
**Pull request by hyugabokko**
#### Summary

PR #1963 has a improvement that resolves #1732, but appears to have been left as a work in progress.
This PR takes a portion of the code modified in #1963 and makes additional code modifications.

#### Changes

Specifically, the following code changes were made
- Based on PR #1963, I edited the filterComponent.tsx and the filterEntry.tsx so that a property of type "person" appears as a filter item.
- When attempting to display the value of a filter, the userlist of the board will be displayed in the case of a property of type "person".
  - For other property types, the value is added to the options at the stage of adding the property to the card. However, for a property of type "person", options must be changed each time a user is added or removed from the board. Therefore, I have determined that it is appropriate to retrieve the userlist when displaying the filter and treat it as a options. This implementation is controversial so it should be specifically checked during the review process.
- To get the userlist for a board in the filterEntry.tsx, I have added the userlist to state in a unit test (filterEntry.test.tsx).

The following gifs are shown as proof of operation.

#### Behavior
Animation

#### Ticket Link
Fixes #1732

### CODE REVIEW

**Review by jespino — APPROVED** [review]
Nice one, I'm doing a refactor around properties, and I going to take advantage of this changes to include person filtering. Thanks!

**Comment by sbishel** [comment]
@jespino - With your properties refactor, can this PR be closed or is there still value in the PR

**Comment by Tonfa** [comment]
How can we move this PR forward? Very critical feature

**Comment by wuwinson** [comment]
@jespino Following-up on this. Is there any additional work needed on this PR after your refactor? This is one of the top requested features by our users and it would be amazing if we could get this in. Thanks!

**Comment by sbishel** [comment]
Closing as no longer relevent.

**Comment by vonunwerth** [comment]
In case anyone is wondering if this feature now exists:
The [changelog](https://docs.mattermost.com/install/self-managed-changelog.html) says: "Added support for person, multi-person and date property filters in boards." as of Mattermost 7.8
"See the [docs](https://docs.mattermost.com/boards/groups-filter-sort.html#work-with-groups-filter-and-sort) for more details.

**Pull request closed without merging**
