### PR TITLE
Allowing subpath in development environment

### LINKED ISSUE #2972: Bug: `serverRoot` with subpath doesn't work locally
## Steps to reproduce the behavior

1. Go to `config.json` and modify the `serverRoot` to contain a subpath e.g. `http://localhost:8000/localboard`
2. Start up Focalboard (personal server) locally
3. Go to the `serverRoot` you configured
4. Note the boilerplate React HTML document loads, but none of the assets e.g. JS load

## Expected behavior

Subpathing to work locally for testing e.g. to verify URLs are being build correctly.

## Screenshots (optional)

image

image

## Edition and Platform

 - Edition: Personal Server (locally)
 - Version: `main`
 - Browser and OS: FF100 on Mac

## Additional context (optional)

Sev 2 as the workaround (as I understand it) is to also run Nginx (or similar) locally to reverse-proxy and test that way.

- Board: https://community.mattermost.com/boards/workspace/b1ni7nprjpfwpb566k1gk8z9nw/886d2280-e88e-4065-8c85-1b62578f192e/f30dcb19-a0e8-45d2-8768-a9489f6e7fe8/c79q3sin15jfsupuwm85595epdc
- @harshilsharma63's `nginx.conf`: https://community-daily.mattermost.com/core/pl/uju4oqetmbftifqqgajmosjfjh

### PR DESCRIPTION
**Pull request by jespino**
Fixes #2972

### CODE REVIEW

**Review by wiggin77 — APPROVED** [review]
LGTM :+1:

**Comment by Pinjasaur** [comment]
I'm having difficulty validating this works locally.

1. I pulled your forked repo & branch locally
2. `make prebuild && make`
3. modify `config.json` to have a trailing `serverRoot` subpath: `"http://localhost:8000/localboard"`
4. `FOCALBOARD_HTTP_SERVER_BASEPATH=localboard bin/focalboard-server`
5. `http://localhost:8000/localboard/static/main.js` serves the `index.html` instead of the expect asset

Any idea where I'm going wrong @jespino ?

**Comment by jespino** [comment]
@Pinjasaur can you try passing the BASEPATH as `/localboard` with the `/`. Probably we can add automatically if it is not there.

**Comment by Pinjasaur** [comment]
> @Pinjasaur can you try passing the BASEPATH as `/localboard` with the `/`. Probably we can add automatically if it is not there.

Ahh, got it. Thanks! Needed a trailing slash in my browser too, otherwise 404: http://localhost:8000/localboard/

**Review by Pinjasaur — APPROVED** [review]
LGTM. Where would it make sense to document this?

**Pull request merged**
