### PR TITLE
Vertically Center Aligned createdBy, createdAt, lastModifiedBy and lastModifiedAt Properties

### PR DESCRIPTION
**Pull request by rakshit087**
#### Summary
Fixes the Vertical Alignment of createdBy, createdAt, lastModifiedBy and lastModifiedAt Properties by making them flex and aligning items at center.

#### Ticket Link
Partially fixes https://github.com/mattermost/focalboard/issues/1096

### CODE REVIEW

**Comment by rakshit087** [comment]
> Looks good to me. Thanks @rakshit087! 🎉
> 
> By the way, you need to sign the CLA before we can merge this PR.

How can I sign the CLA?

**Comment by rakshit087** [comment]
> > How can I sign the CLA?
> 
> You have to go here: https://mattermost.org/mattermost-contributor-agreement/ and introduce your information.

Done! Thank You 👍

**Comment by jespino** [comment]
@rakshit087 Great, thanks! now the CI is complaining about the lack of new lines in the last line of the added scss files. Do you mind to fix that?

**Comment by rakshit087** [comment]
Oh, Sure in a minute, forgot to add new lines. Kind of new to opensource, shall I close this PR and make a new one or my latest commits will be automatically included?

**Comment by rakshit087** [comment]
Here is a Screen Shot after the latest commit
image

**Comment by emilyacook** [comment]
Thanks for participating in Hacktoberfest! You can claim your sticker set here: https://get.printfection.com/hacktober21/4144583267 @rakshit087

**Comment by rakshit087** [comment]
Thank You :))

**Review by asaadmahmood — APPROVED** [review]
LGTM

**Comment by rakshit087** [comment]
Thank you for reviewing, can you please merge this PR, because I forgot to make a new branch for this PR. 
I won't be able to contribute until this PR is merged.

**Comment by rakshit087** [comment]
Thank you for merging, I will make sure to open a new branch before commiting changes

**Pull request merged**
