### PR TITLE
Adjusting modals and updating close icon on input

### LINKED ISSUE #4434: UI/UX issue: `x` icon is not aligned with text in "Create New Category" modal text input box
Found by QA community contributor @krmh04 on `https://boards-bugbash-76.test.mattermost.cloud/` server, Boards v7.7.0

## Steps to reproduce the behavior

1. Click on the "+" to the right of "Find Boards"
2. Select "Create New Category"
3. Type a name for the category
4. Observed: "x" that appears on the right-hand-side of the category input box is not aligned with category name text

## Expected behavior

"x" that appears on the right-hand-side of the category input box is aligned with category name text

## Screenshots (optional)

image

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v7.7.0
 - Browser and OS: Windows / Chrome

### LINKED ISSUE #4457: Bug: Confirmation dialogs should all be of the same size
## Steps to reproduce the behavior

1. Open Property delete confirmation modal
2. Open card delete confirmation modal
3. Notice they're both of different sizse

## Expected behavior
Should be of the same size

## Edition and Platform
 - Edition: Mattermost Boards (plugin)
 - Version: 7.7
 - Browser and OS: All browsers

## Additional context (optional)

Add any other context about the problem here, and any notes about the severity:
* Sev 1: Affects critical functionality without a workaround
* Sev 2: Affects major functionality with a difficult or non-obvious workaround
* Sev 3: Affects minor, non-critical functionality

### PR DESCRIPTION
**Pull request by asaadmahmood**
#### Summary
Adjusting modals and updating close icon on input

#### Ticket Link
Fixes #4434 
Fixes #4457

### CODE REVIEW

**Comment by harshilsharma63** [comment]
@asaadmahmood looks fine on desktop but the modal looks incorrectly positioned on mobile/small screen-

Screenshot 2023-01-16 at 12 37 27 PM
Screenshot 2023-01-16 at 12 37 36 PM

Notice on the card delete popup, the hamburger menu icon appears through the modal, probably due to too high z-index  value.

**Review by harshilsharma63 — CHANGES_REQUESTED** [review]
Mobile view needs some fixes.

**Comment by asaadmahmood** [comment]
@harshilsharma63 Fixed.

**Review by harshilsharma63 — APPROVED** [review]

**Comment by harshilsharma63** [comment]
LGTM 👍

**Pull request merged**
