### PR TITLE
Fixed multiple safari bugs

### LINKED ISSUE #407: Bug: Cannot paste nor select in description's Card
**Summary:**
In Task Card > description, cannot paste nor select anything

**Steps to reproduce the behavior:**
1. open a task card
2. click on description field
3. try to paste / select anything

**Expected behavior:**
Insert pasted text / select text

**Platform:**
 - FocalBoard Personal Desktop 0.6.7
 - OS: Linux Ubuntu 18.04

### PR DESCRIPTION
**Pull request by harshilsharma63**
#### Summary
Fixed multiple bugs faced in Safari and MacOS desktop app regaled to text editor in comments and description.

Fixes #407 #482 and #506

### CODE REVIEW

**Review by sbishel — APPROVED** [review]
I'm not sure how you figured this one out, but nice work. Works for me now in both FF and Chrome.

**Comment by fernandascovino** [comment]
hey! I still can't use copy/paste in Mac app... I'm on v0.6.7

**Comment by harshilsharma63** [comment]
> hey! I still can't use copy/paste in Mac app... I'm on v0.6.7, when is the new version coming out with this feature? :)

@chenilim  can you please answer this one?

**Comment by chenilim** [comment]
There was a bug in v0.6.7 where the text couldn't be selected while editing the markdown content of a card (this was a regression from 0.6.5). I just checked, and this appears to be fixed in the latest build, so should be in the next release.

Note that there is another [open issue](https://github.com/mattermost/focalboard/issues/263) tracking the ability to copy / paste without first editing the content.

**Comment by fernandascovino** [comment]
nice! do you have a date for the next release? otherwise I can downgrade it here to v0.6.5

about the editing, I actually cannot copy/paste (or select) the text description of cards, even on edit mode... other fields such as title and summary works fine.

**Comment by chenilim** [comment]
Thanks @fernandascovino! We're planning on cutting RC1 of the June release tomorrow. If you need something sooner, you can try running against [0.6.5 RC3](https://github.com/mattermost/focalboard/releases/tag/v0.6.5-rc3), also to verify that the issue doesn't repro there for you.

**Pull request merged**
