### PR TITLE
Update to v0.12.1

### PR DESCRIPTION
**Pull request by sbishel**
#### Summary
Update version to v0.12.1

### CODE REVIEW

**Review by chenilim — APPROVED** [review]
Looks good, but I believe `topBar.test.tsx.snap` also needs to be updated to pass CI?

**Comment by sbishel** [comment]
> Looks good, but I believe `topBar.test.tsx.snap` also needs to be updated to pass CI?

It passes in a version, so it doesn't get updated with the version change.

**Comment by amyblais** [comment]
@harshilsharma63 Please help prioritize this PR review for a dot release.

**Review by harshilsharma63 — APPROVED** [review]

**Comment by harshilsharma63** [comment]
> @harshilsharma63 Please help prioritize this PR review for a dot release.

Done. Sorry for the delay.

**Pull request merged**
