### PR TITLE
User updates

### PR DESCRIPTION
**Pull request by sbishel**
#### Summary
Returns LastName, FirstName, and Nickname for channels users.
Returns config setting for `TeamSettings.TeammateNameDisplay`
Uses setting and displays users in Permissions and User property as requested.

#### Ticket Link
  Fixes https://github.com/mattermost/focalboard/issues/2933

### CODE REVIEW

**Comment by sbishel** [comment]
Screen Shot 2022-06-20 at 12 44 51 PM
Screen Shot 2022-06-20 at 12 41 42 PM
Screen Shot 2022-06-20 at 12 41 33 PM

**Review by harshilsharma63 — APPROVED** [review]

**Comment by harshilsharma63** [comment]
@sbishel it works fine but I was confused with it because I thought it would read the user's Teammate Name Display" setting. If it's possible, it would be nicer to use the user's preference of how they wanna view a teammate's name rather than the team-level setting. Channels seem to be doing the same - preferring user-level settings over team-level.

This can be done later too.

**Comment by sbishel** [comment]
Thanks @harshilsharma63 - I didn't realize there was a personal setting. I agree we should be using this on. I will update.

**Comment by harshilsharma63** [comment]
@sbishel I'm not 100% sure whats the exact logic channels use to determine which setting to use finally, so worth checking channel's implementation.

**Comment by harshilsharma63** [comment]
Also another extension for this would be the @ mention autocomplete list in comment adn description.

**Comment by sbishel** [comment]
Added to @mentions as well.
Screen Shot 2022-07-05 at 4 59 31 PM

**Review by harshilsharma63 — APPROVED** [review]
LGTM 👍

**Pull request merged**
