### PR TITLE
[MM-40214] Implement App Bar component

### PR DESCRIPTION
**Pull request by mickmister**
#### Summary

This PR makes it so the plugin registers its own component to the App Bar. The core webapp makes it so the component is only mounted if the `AppBarEnabled` feature flag is on. This logic is only in the core webapp, and not in the plugin's source.

The plugin registers its usual channel header component, while simultaneously register the App Bar component. This is so the webapp can show one or the other when the App Bar feature flag is enabled or disabled. The plugin itself then doesn't need to watch this feature flag, and the webapp can manage the effects of the flag.

#### Ticket Link

Fixes https://mattermost.atlassian.net/browse/MM-40214

#### Screenshots

Denim

Onyx

### CODE REVIEW

**Review by jespino — APPROVED** [review]
LGTM

**Comment by harshilsharma63** [comment]
Looks great!
Screenshot 2022-01-20 at 4 47 57 PM

**Review by harshilsharma63 — APPROVED** [review]
LGTM 👍

**Comment by mickmister** [comment]
Thanks @harshilsharma63, I realized after I had submitted these PRs that I had forgotten to post screenshots. Description updated for future references to the PR.

**Comment by mickmister** [comment]
@DHaussermann This is ready for testing

**Comment by dipak-demansol** [comment]
LDTM, Tested in The Web and Desktop app With all The Theme.

**Comment by mickmister** [comment]
@DHaussermann Is this good to merge?

**Pull request merged**
