### PR TITLE
`main` Cherrypick: Hidden card view via direct URL & unfurl (#3071)

### PR DESCRIPTION
**Pull request by Pinjasaur**
#### Summary

This is an initial cherrypick of #3071 to `main` with merge conflicts resolved. However, other PRs got merged before mine so changes e.g. `limited` on a `Block` type and additions to the `WSClient` prevent this from fully working until they're cherrypicked into `main` as well. CI is expected to fail at this point.

Once `main` has the changes, I'm expecting to need to `npm run i18n-extract` along with verifying tests and everything still working as expected.

#### Ticket Link

#3071

### CODE REVIEW

**Review by sbishel — APPROVED** [review]

**Review by Rajat-Dabade — APPROVED** [review]

**Comment by Pinjasaur** [comment]
Best I can tell, last blocking part of getting this PR to `main` is there's some Typescript type errors going on with all three SVG `.tsx` components. Not immediately clear to me what the root cause is specifically.

**Pull request merged**
