### PR TITLE
disabling autoExpanding

### PR DESCRIPTION
**Pull request by kirtilodha**
#### Summary

It disables auto-expanding the height of the row.
#### Ticket Link

  Fixes https://github.com/mattermost/focalboard/issues/1024

### CODE REVIEW

**Review by jespino — APPROVED** [review]
This has unrelated changes, but both PRs looks good to me.

**Comment by emilyacook** [comment]
Thanks for participating in Hacktoberfest! You can claim your sticker set here: https://get.printfection.com/hacktober21/4144583267 @kirtilodha

**Comment by chenilim** [comment]
Just following up on this. It appears that the issue #1024 has been closed. Should we close this PR? cc @jespino.

**Comment by chenilim** [comment]
Closing this PR as the source issue was closed.

**Pull request closed without merging**
