### PR TITLE
Updating date when prop has changed

### PR DESCRIPTION
**Pull request by BenCookie95**
#### Summary
Date property on a card was not updating when you changed it's value elsewhere

#### Ticket Link
https://github.com/mattermost/focalboard/issues/4474

### CODE REVIEW

**Review by sbishel — APPROVED** [review]

**Review by calebroseland — APPROVED** [review]

**Comment by lindy65** [comment]
Hi @BenCookie95 - please create a corresponding PR in the server repo so I can create a spinwick and test there. Thanks :)

**Comment by BenCookie95** [comment]
@lindy65 PR is building here right now, should be available soon https://github.com/mattermost/mattermost-server/pull/22419

**Comment by lindy65** [comment]
Hi @BenCookie95 

I tested on the spinwick on https://github.com/mattermost/mattermost-server/pull/22419 according to repro steps on https://github.com/mattermost/focalboard/issues/4474

Changing the date within a card shows the date change instantly.
image

However, when I close the card, the old date is still displayed until I refresh
image

image

**Comment by BenCookie95** [comment]
> Hi @BenCookie95
> 
> I tested on the spinwick on [mattermost/mattermost-server#22419](https://github.com/mattermost/mattermost-server/pull/22419) according to repro steps on #4474
> 
> Changing the date within a card shows the date change instantly. image
> 
> However, when I close the card, the old date is still displayed until I refresh image
> 
> image

Thanks Lindy, I'll take a look

**Comment by lindy65** [comment]
Thanks @BenCookie95

**Comment by BenCookie95** [comment]
@lindy65 Should be working here now https://mattermost-server-pr-22419.test.mattermost.cloud/

**Review by lindy65 — APPROVED** [review]
Thanks @BenCookie95 - the issue is indeed fixed.  Updating the date property within the card, then closing the card, shows the updated date on the card.

**Pull request merged**
